In [1]:
#10-04-2023

In [2]:
numbers=[1,2,3,4,5,6]
squares=[num**2 for num in numbers]
print(squares)

[1, 4, 9, 16, 25, 36]

In [4]:
#filtering even numbers in the list

numbers=[1,2,3,4,5,6,7,8,9]
even=[num for num in numbers if num%2==0]
print(even)

[2, 4, 6, 8]

In [5]:
strings=['Hello','world','how','are','you']
upper_strings=[i.upper() for i in strings]
print(upper_strings)

['HELLO', 'WORLD', 'HOW', 'ARE', 'YOU']

In [6]:
names=['Bob','John','Xiao','Virat']
lower=[i.lower() for i in names]
print(lower)

['bob', 'john', 'xiao', 'virat']

In [7]:
names=['Bob','John','Xiao','Develliers']
name_lengths=[(name,len(name)) for name in names]
print(name_lengths)

[('Bob', 3), ('John', 4), ('Xiao', 4), ('Develliers', 10)]

In [8]:
m=[[1,2,3],[2,3,4],[4,5,6],[5,6,7,7]]
flattened=[num for row in m for num in row]
print(flattened)

[1, 2, 3, 2, 3, 4, 4, 5, 6, 5, 6, 7, 7]

In [9]:
evens=[num for num in range(1,11) if num%2==0]
print(evens)

[2, 4, 6, 8, 10]

In [10]:
nested_list=[[1,2,3],[4,5,6],[7,8,9]]
total_list=sum(num for sublist in nested_list for num in sublist)
print(total_list)

45

In [12]:
string='Hello, World!'
vowels='aeiouAEIOU'
result=''.join([char for char in string if char not in vowels])
print(result)

Hll, Wrld!

In [13]:
# Write a Python program to create a list of all the elements of two lists that are uncommon using list comprehension.
list1=[1,2,3,4,5]
list2=[3,4,5,6,7,7,8]
uncommon_el=[x for x in list1 if x not in list2]
print(uncommon_el)

[1, 2]

In [14]:
# Write a Python program to create a list of all the elements of two lists that are common using list comprehension.
list1=[1,2,3,4,5]
list2=[3,4,5,6,7,7,8]
uncommon_el=[x for x in list1 if x in list2]
print(uncommon_el)

[3, 4, 5]

In [17]:
# Write a Python program to create a list of all the elements of two lists that are not common using list comprehension.
list1=[1,2,3,4,5]
list2=[3,4,5,6,7,8]
unique_el=[x for x in list1 if x not in list2]+[x for x in list2 if x not in list1]
print(unique_el)

[1, 2, 6, 7, 8]

In [18]:
##Write a Python program to create a list of all the positive numbers in a given list using list comprehension.
list1=[-1,2,3,-4,-5,0,1,2,3,-10,-12,13]
pos_num=[num for num in list1 if num>0]
print(pos_num)

[2, 3, 1, 2, 3, 13]

In [ ]:
# write a Python program to create a list of the first 10 prime numbers using list comprehension.

In [20]:
##Write a Python program to create a list of all the negetive numbers in a given list using list comprehension.
neg_num=[num for num in list1 if num<0]
print(neg_num)

[-1, -4, -5, -10, -12]

In [21]:
#Write a Python program to create a list of all the odd numbers in a given list using list comprehension.
odd_num=[num for num in list1 if num%2!=0]
print(odd_num)

[-1, 3, -5, 1, 3, 13]

In [24]:
#Write a Python program to create a list of all the even numbers in a given list using list comprehension.
even_num=[num for num in list1 if num%2==0]
print(even_num)

[2, -4, 0, 2, -10, -12]

In [23]:
#Write a Python program to create a list of all the words in a given sentence that have more than 4 letters 
#using list comprehension.

sentense='This is a sample sentense with some words having more than four letters'
words=sentense.split()
print(words)
long_words=[word for word in words if len(word)>4]
print(long_words)

['This', 'is', 'a', 'sample', 'sentense', 'with', 'some', 'words', 'having', 'more', 'than', 'four', 'letters']
['sample', 'sentense', 'words', 'having', 'letters']

In [25]:
# Write a Python program to create a list of all the words in a given sentence that start with a vowel using list comprehension.
sen='An apple a day keeps the doctor away'
list2=sen.split()
words_start_with_vowel=[word for word in list2 if word[0].lower() in 'aeiou']
print(words_start_with_vowel)

['An', 'apple', 'a', 'away']

In [26]:
words_end_with_vowel=[word for word in list2 if word[-1].lower() in 'aeiou']
print(words_end_with_vowel)

['apple', 'a', 'the']

In [27]:
squares_of_evens=[num**2 for num in range(2,21,2)]
print(squares_of_evens)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400]

In [28]:
#to extract upper case letters in a string using list comprehension
string='Hello, WORLD!'
uppercase_letters=[i for i in string if i.isupper()]
print(uppercase_letters)

['H', 'W', 'O', 'R', 'L', 'D']

In [31]:
# Write a Python program to create a list of all the numbers in a given list that will not be divisible by 3 and 5 
#using list comprehension.

numbers=[1,2,3,4,5,6,7,8,9]
not_div_by_3_and_5=[i for i in numbers if i%3!=0 and i%5!=0]
print(not_div_by_3_and_5)

[1, 2, 4, 7, 8]

In [33]:

primes=[x for x in range(2,2*10) if all(x%i!=0 for i in range(2, int(x**0.5)+1))]
print(primes)

[2, 3, 5, 7, 11, 13, 17, 19]

# Itertools module

In [34]:
import itertools

In [ ]:
#used for effciency memory management
#

In [35]:
counter=itertools.count()
print(next(counter))

0

In [36]:
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))

1
2
3
4
5

In [38]:
data=[1,2,3,4,5,6,7]
ans=[]
for i in enumerate(data):
    ans.append(i)

In [39]:
ans

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7)]

In [42]:
#zip function takes 2 iterables inside the brackets and combines together elementarily
daily_data=list(zip(itertools.count(), data))
print(daily_data)

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7)]

In [43]:
counter=itertools.count(start=10)

In [44]:
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))

10
11
12
13
14

In [46]:
counter=itertools.count(start=5, step=2.5)
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))

5
7.5
10.0
12.5
15.0

In [54]:
daily_data2=list(itertools.zip_longest(range(10), data))

In [55]:
daily_data2
#after the iterables are over, none was added as the output

[(0, 1),
 (1, 2),
 (2, 3),
 (3, 4),
 (4, 5),
 (5, 6),
 (6, 7),
 (7, None),
 (8, None),
 (9, None)]

In [57]:
counter=itertools.cycle([10,20,30,40])
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))

10
20
30
40
10
20
30
40
10
20

In [58]:
counter=itertools.cycle(('raj','Ram','Ranjith','Bharat'))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))

raj
Ram
Ranjith
Bharat
raj
Ram
Ranjith
Bharat
raj
Ram

In [59]:
counter=itertools.repeat(2)
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))

2
2
2
2
2
2

In [62]:
counter=itertools.repeat(2, times=3)
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))
print(next(counter))

2
2
2

StopIteration:

# map function

In [63]:
a=input().split()

5

In [64]:
l=list(map(int, input().split()))
print(l)

20 23 24 25 38
[20, 23, 24, 25, 38]

In [65]:
l=list(map(str, input().split()))
l

sdsff asfdfs sdfds 1 12 3 4423

['sdsff', 'asfdfs', 'sdfds', '1', '12', '3', '4423']

In [5]:
#permutations and combinations
letters = ['a', 'b', 'c', 'd']
numbers = [0, 1, 2, 3]
names = ['Brad', 'Nicole']

people = [
    {
        'name': 'John Doe',
        'city': 'Gotham',
        'state': 'NY'
    },
    {
        'name': 'Jane Doe',
        'city': 'Kings Landing',
        'state': 'NY'
    },
    {
        'name': 'Brad Pitt',
        'city': 'Boulder',
        'state': 'CO'
    },
    {
        'name': 'Al Einstein',
        'city': 'Denver',
        'state': 'CO'
    },
    {
        'name': 'John Henry',
        'city': 'Hinton',
        'state': 'WV'
    },
    {
        'name': 'Randy Moss',
        'city': 'Rand',
        'state': 'WV'
    },
    {
        'name': 'Nicole K',
        'city': 'Asheville',
        'state': 'NC'
    },
    {
        'name': 'Jim Doe',
        'city': 'Charlotte',
        'state': 'NC'
    },
    {
        'name': 'Jane Taylor',
        'city': 'Faketown',
        'state': 'NC'
    }
]

In [70]:
print(letters)

['a', 'b', 'c', 'd']

In [72]:
results=itertools.permutations(people,2)
for i in results:
    print(i)

({'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'}, {'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'})
({'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'}, {'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'})
({'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'}, {'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'})
({'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'}, {'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'})
({'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'}, {'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'})
({'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'}, {'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'})
({'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'}, {'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'})
({'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'}, {'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'})
({'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'}, {'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'})
({'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'}, {'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'})
({'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'}, {'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'})
({'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'}, {'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'})
({'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'}, {'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'})
({'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'}, {'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'})
({'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'}, {'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'})
({'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'}, {'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'})
({'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'}, {'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'})
({'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'}, {'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'})
({'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'}, {'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'})
({'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'}, {'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'})
({'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'}, {'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'})
({'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'}, {'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'})
({'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'}, {'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'})
({'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'}, {'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'})
({'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'}, {'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'})
({'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'}, {'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'})
({'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'}, {'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'})
({'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'}, {'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'})
({'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'}, {'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'})
({'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'}, {'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'})
({'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'}, {'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'})
({'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'}, {'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'})
({'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'}, {'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'})
({'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'}, {'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'})
({'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'}, {'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'})
({'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'}, {'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'})
({'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'}, {'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'})
({'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'}, {'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'})
({'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'}, {'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'})
({'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'}, {'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'})
({'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'}, {'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'})
({'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'}, {'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'})
({'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'}, {'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'})
({'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'}, {'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'})
({'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'}, {'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'})
({'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'}, {'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'})
({'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'}, {'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'})
({'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'}, {'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'})
({'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'}, {'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'})
({'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'}, {'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'})
({'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'}, {'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'})
({'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'}, {'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'})
({'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'}, {'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'})
({'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'}, {'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'})
({'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'}, {'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'})
({'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'}, {'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'})
({'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'}, {'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'})
({'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'}, {'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'})
({'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'}, {'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'})
({'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'}, {'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'})
({'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'}, {'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'})
({'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'}, {'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'})
({'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'}, {'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'})
({'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'}, {'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'})
({'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'}, {'name': 'John Doe', 'city': 'Gotham', 'state': 'NY'})
({'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'}, {'name': 'Jane Doe', 'city': 'Kings Landing', 'state': 'NY'})
({'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'}, {'name': 'Brad Pitt', 'city': 'Boulder', 'state': 'CO'})
({'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'}, {'name': 'Al Einstein', 'city': 'Denver', 'state': 'CO'})
({'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'}, {'name': 'John Henry', 'city': 'Hinton', 'state': 'WV'})
({'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'}, {'name': 'Randy Moss', 'city': 'Rand', 'state': 'WV'})
({'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'}, {'name': 'Nicole K', 'city': 'Asheville', 'state': 'NC'})
({'name': 'Jane Taylor', 'city': 'Faketown', 'state': 'NC'}, {'name': 'Jim Doe', 'city': 'Charlotte', 'state': 'NC'})

In [73]:
results=itertools.permutations(letters, 2)
for i in results:
    print(i)

('a', 'b')
('a', 'c')
('a', 'd')
('b', 'a')
('b', 'c')
('b', 'd')
('c', 'a')
('c', 'b')
('c', 'd')
('d', 'a')
('d', 'b')
('d', 'c')

In [74]:
results1=itertools.combinations(letters, 2)
for i in results1:
    print(i)
#(a,b) and (b,a) will not be repeated

('a', 'b')
('a', 'c')
('a', 'd')
('b', 'c')
('b', 'd')
('c', 'd')

In [75]:
numbers

[0, 1, 2, 3]

In [79]:
list(itertools.combinations(numbers,4))

[(0, 1, 2, 3)]

In [80]:
list(itertools.permutations(numbers,4))

[(0, 1, 2, 3),
 (0, 1, 3, 2),
 (0, 2, 1, 3),
 (0, 2, 3, 1),
 (0, 3, 1, 2),
 (0, 3, 2, 1),
 (1, 0, 2, 3),
 (1, 0, 3, 2),
 (1, 2, 0, 3),
 (1, 2, 3, 0),
 (1, 3, 0, 2),
 (1, 3, 2, 0),
 (2, 0, 1, 3),
 (2, 0, 3, 1),
 (2, 1, 0, 3),
 (2, 1, 3, 0),
 (2, 3, 0, 1),
 (2, 3, 1, 0),
 (3, 0, 1, 2),
 (3, 0, 2, 1),
 (3, 1, 0, 2),
 (3, 1, 2, 0),
 (3, 2, 0, 1),
 (3, 2, 1, 0)]

In [76]:
results=itertools.product(numbers, repeat=4)

for i in results:
    print(i)
    #repeat is going to gives us all ways we can arrange where repeats are allowed
    #

(0, 0, 0, 0)
(0, 0, 0, 1)
(0, 0, 0, 2)
(0, 0, 0, 3)
(0, 0, 1, 0)
(0, 0, 1, 1)
(0, 0, 1, 2)
(0, 0, 1, 3)
(0, 0, 2, 0)
(0, 0, 2, 1)
(0, 0, 2, 2)
(0, 0, 2, 3)
(0, 0, 3, 0)
(0, 0, 3, 1)
(0, 0, 3, 2)
(0, 0, 3, 3)
(0, 1, 0, 0)
(0, 1, 0, 1)
(0, 1, 0, 2)
(0, 1, 0, 3)
(0, 1, 1, 0)
(0, 1, 1, 1)
(0, 1, 1, 2)
(0, 1, 1, 3)
(0, 1, 2, 0)
(0, 1, 2, 1)
(0, 1, 2, 2)
(0, 1, 2, 3)
(0, 1, 3, 0)
(0, 1, 3, 1)
(0, 1, 3, 2)
(0, 1, 3, 3)
(0, 2, 0, 0)
(0, 2, 0, 1)
(0, 2, 0, 2)
(0, 2, 0, 3)
(0, 2, 1, 0)
(0, 2, 1, 1)
(0, 2, 1, 2)
(0, 2, 1, 3)
(0, 2, 2, 0)
(0, 2, 2, 1)
(0, 2, 2, 2)
(0, 2, 2, 3)
(0, 2, 3, 0)
(0, 2, 3, 1)
(0, 2, 3, 2)
(0, 2, 3, 3)
(0, 3, 0, 0)
(0, 3, 0, 1)
(0, 3, 0, 2)
(0, 3, 0, 3)
(0, 3, 1, 0)
(0, 3, 1, 1)
(0, 3, 1, 2)
(0, 3, 1, 3)
(0, 3, 2, 0)
(0, 3, 2, 1)
(0, 3, 2, 2)
(0, 3, 2, 3)
(0, 3, 3, 0)
(0, 3, 3, 1)
(0, 3, 3, 2)
(0, 3, 3, 3)
(1, 0, 0, 0)
(1, 0, 0, 1)
(1, 0, 0, 2)
(1, 0, 0, 3)
(1, 0, 1, 0)
(1, 0, 1, 1)
(1, 0, 1, 2)
(1, 0, 1, 3)
(1, 0, 2, 0)
(1, 0, 2, 1)
(1, 0, 2, 2)
(1, 0, 2, 3)
(1, 0, 3, 0)
(1, 0, 3, 1)
(1, 0, 3, 2)
(1, 0, 3, 3)
(1, 1, 0, 0)
(1, 1, 0, 1)
(1, 1, 0, 2)
(1, 1, 0, 3)
(1, 1, 1, 0)
(1, 1, 1, 1)
(1, 1, 1, 2)
(1, 1, 1, 3)
(1, 1, 2, 0)
(1, 1, 2, 1)
(1, 1, 2, 2)
(1, 1, 2, 3)
(1, 1, 3, 0)
(1, 1, 3, 1)
(1, 1, 3, 2)
(1, 1, 3, 3)
(1, 2, 0, 0)
(1, 2, 0, 1)
(1, 2, 0, 2)
(1, 2, 0, 3)
(1, 2, 1, 0)
(1, 2, 1, 1)
(1, 2, 1, 2)
(1, 2, 1, 3)
(1, 2, 2, 0)
(1, 2, 2, 1)
(1, 2, 2, 2)
(1, 2, 2, 3)
(1, 2, 3, 0)
(1, 2, 3, 1)
(1, 2, 3, 2)
(1, 2, 3, 3)
(1, 3, 0, 0)
(1, 3, 0, 1)
(1, 3, 0, 2)
(1, 3, 0, 3)
(1, 3, 1, 0)
(1, 3, 1, 1)
(1, 3, 1, 2)
(1, 3, 1, 3)
(1, 3, 2, 0)
(1, 3, 2, 1)
(1, 3, 2, 2)
(1, 3, 2, 3)
(1, 3, 3, 0)
(1, 3, 3, 1)
(1, 3, 3, 2)
(1, 3, 3, 3)
(2, 0, 0, 0)
(2, 0, 0, 1)
(2, 0, 0, 2)
(2, 0, 0, 3)
(2, 0, 1, 0)
(2, 0, 1, 1)
(2, 0, 1, 2)
(2, 0, 1, 3)
(2, 0, 2, 0)
(2, 0, 2, 1)
(2, 0, 2, 2)
(2, 0, 2, 3)
(2, 0, 3, 0)
(2, 0, 3, 1)
(2, 0, 3, 2)
(2, 0, 3, 3)
(2, 1, 0, 0)
(2, 1, 0, 1)
(2, 1, 0, 2)
(2, 1, 0, 3)
(2, 1, 1, 0)
(2, 1, 1, 1)
(2, 1, 1, 2)
(2, 1, 1, 3)
(2, 1, 2, 0)
(2, 1, 2, 1)
(2, 1, 2, 2)
(2, 1, 2, 3)
(2, 1, 3, 0)
(2, 1, 3, 1)
(2, 1, 3, 2)
(2, 1, 3, 3)
(2, 2, 0, 0)
(2, 2, 0, 1)
(2, 2, 0, 2)
(2, 2, 0, 3)
(2, 2, 1, 0)
(2, 2, 1, 1)
(2, 2, 1, 2)
(2, 2, 1, 3)
(2, 2, 2, 0)
(2, 2, 2, 1)
(2, 2, 2, 2)
(2, 2, 2, 3)
(2, 2, 3, 0)
(2, 2, 3, 1)
(2, 2, 3, 2)
(2, 2, 3, 3)
(2, 3, 0, 0)
(2, 3, 0, 1)
(2, 3, 0, 2)
(2, 3, 0, 3)
(2, 3, 1, 0)
(2, 3, 1, 1)
(2, 3, 1, 2)
(2, 3, 1, 3)
(2, 3, 2, 0)
(2, 3, 2, 1)
(2, 3, 2, 2)
(2, 3, 2, 3)
(2, 3, 3, 0)
(2, 3, 3, 1)
(2, 3, 3, 2)
(2, 3, 3, 3)
(3, 0, 0, 0)
(3, 0, 0, 1)
(3, 0, 0, 2)
(3, 0, 0, 3)
(3, 0, 1, 0)
(3, 0, 1, 1)
(3, 0, 1, 2)
(3, 0, 1, 3)
(3, 0, 2, 0)
(3, 0, 2, 1)
(3, 0, 2, 2)
(3, 0, 2, 3)
(3, 0, 3, 0)
(3, 0, 3, 1)
(3, 0, 3, 2)
(3, 0, 3, 3)
(3, 1, 0, 0)
(3, 1, 0, 1)
(3, 1, 0, 2)
(3, 1, 0, 3)
(3, 1, 1, 0)
(3, 1, 1, 1)
(3, 1, 1, 2)
(3, 1, 1, 3)
(3, 1, 2, 0)
(3, 1, 2, 1)
(3, 1, 2, 2)
(3, 1, 2, 3)
(3, 1, 3, 0)
(3, 1, 3, 1)
(3, 1, 3, 2)
(3, 1, 3, 3)
(3, 2, 0, 0)
(3, 2, 0, 1)
(3, 2, 0, 2)
(3, 2, 0, 3)
(3, 2, 1, 0)
(3, 2, 1, 1)
(3, 2, 1, 2)
(3, 2, 1, 3)
(3, 2, 2, 0)
(3, 2, 2, 1)
(3, 2, 2, 2)
(3, 2, 2, 3)
(3, 2, 3, 0)
(3, 2, 3, 1)
(3, 2, 3, 2)
(3, 2, 3, 3)
(3, 3, 0, 0)
(3, 3, 0, 1)
(3, 3, 0, 2)
(3, 3, 0, 3)
(3, 3, 1, 0)
(3, 3, 1, 1)
(3, 3, 1, 2)
(3, 3, 1, 3)
(3, 3, 2, 0)
(3, 3, 2, 1)
(3, 3, 2, 2)
(3, 3, 2, 3)
(3, 3, 3, 0)
(3, 3, 3, 1)
(3, 3, 3, 2)
(3, 3, 3, 3)

In [84]:
results=itertools.product(numbers, repeat=3)

for i in results:
    print(i)
    #repeat is going to gives us all ways we can arrange where repeats are allowed
    #

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 0, 3)
(0, 1, 0)
(0, 1, 1)
(0, 1, 2)
(0, 1, 3)
(0, 2, 0)
(0, 2, 1)
(0, 2, 2)
(0, 2, 3)
(0, 3, 0)
(0, 3, 1)
(0, 3, 2)
(0, 3, 3)
(1, 0, 0)
(1, 0, 1)
(1, 0, 2)
(1, 0, 3)
(1, 1, 0)
(1, 1, 1)
(1, 1, 2)
(1, 1, 3)
(1, 2, 0)
(1, 2, 1)
(1, 2, 2)
(1, 2, 3)
(1, 3, 0)
(1, 3, 1)
(1, 3, 2)
(1, 3, 3)
(2, 0, 0)
(2, 0, 1)
(2, 0, 2)
(2, 0, 3)
(2, 1, 0)
(2, 1, 1)
(2, 1, 2)
(2, 1, 3)
(2, 2, 0)
(2, 2, 1)
(2, 2, 2)
(2, 2, 3)
(2, 3, 0)
(2, 3, 1)
(2, 3, 2)
(2, 3, 3)
(3, 0, 0)
(3, 0, 1)
(3, 0, 2)
(3, 0, 3)
(3, 1, 0)
(3, 1, 1)
(3, 1, 2)
(3, 1, 3)
(3, 2, 0)
(3, 2, 1)
(3, 2, 2)
(3, 2, 3)
(3, 3, 0)
(3, 3, 1)
(3, 3, 2)
(3, 3, 3)

In [82]:
results=itertools.combinations_with_replacement(numbers, 4)

for i in results:
    print(i)

(0, 0, 0, 0)
(0, 0, 0, 1)
(0, 0, 0, 2)
(0, 0, 0, 3)
(0, 0, 1, 1)
(0, 0, 1, 2)
(0, 0, 1, 3)
(0, 0, 2, 2)
(0, 0, 2, 3)
(0, 0, 3, 3)
(0, 1, 1, 1)
(0, 1, 1, 2)
(0, 1, 1, 3)
(0, 1, 2, 2)
(0, 1, 2, 3)
(0, 1, 3, 3)
(0, 2, 2, 2)
(0, 2, 2, 3)
(0, 2, 3, 3)
(0, 3, 3, 3)
(1, 1, 1, 1)
(1, 1, 1, 2)
(1, 1, 1, 3)
(1, 1, 2, 2)
(1, 1, 2, 3)
(1, 1, 3, 3)
(1, 2, 2, 2)
(1, 2, 2, 3)
(1, 2, 3, 3)
(1, 3, 3, 3)
(2, 2, 2, 2)
(2, 2, 2, 3)
(2, 2, 3, 3)
(2, 3, 3, 3)
(3, 3, 3, 3)

In [85]:
combined=letters+numbers+names
combined

['a', 'b', 'c', 'd', 0, 1, 2, 3, 'Brad', 'Nicole']

In [10]:
#
combined_chain=itertools.chain(letters,numbers,names)
for i in combined_chain:
    print(i)

a
b
c
d
0
1
2
3
Brad
Nicole

In [7]:
letters

['a', 'b', 'c', 'd']

In [8]:
names

['Brad', 'Nicole']

In [9]:
numbers

[0, 1, 2, 3]

In [17]:
l=[1,2,4,5,6,6]
k=[(lambda x: x**2) for x in l]
k

[<function __main__.<listcomp>.<lambda>(x)>,
 <function __main__.<listcomp>.<lambda>(x)>,
 <function __main__.<listcomp>.<lambda>(x)>,
 <function __main__.<listcomp>.<lambda>(x)>,
 <function __main__.<listcomp>.<lambda>(x)>,
 <function __main__.<listcomp>.<lambda>(x)>]

In [18]:
#islice method
result=itertools.islice(range(10), 5) 
for i in result:
    print(i)

0
1
2
3
4

In [19]:
#islice method
result=itertools.islice(range(10), 1,10,3)  #(iterable_list, start, stop and end)
for i in result:
    print(i)

1
4
7

In [25]:
#we want to grab some lines using islice
with open('testlog.txt','r') as f:
    header=itertools.islice(f,3)
    for line in header:
        print(line, end='')

Date: 2024-04-11
Author: Chirantan
Description: This is a sample log file

In [27]:
#compress function
letters=['a','b','c','d']
selectors=[True, True, False, True]
result=itertools.compress(letters, selectors)

for a in result:
    print(a)

a
b
d

In [31]:
numbers=[0,1,2,3]
def values_lessthan2(n):
    if n<2:
        return True
    else:
        return False

In [32]:
result=filter(values_lessthan2,numbers)
for i in result:
    print(i)

0
1

In [33]:
#accumulate will add values while looping
numbers=[12,13,1,3,1,34,1344,124,233]
result=itertools.accumulate(numbers)
for i in result:
    print(i)

12
25
26
29
30
64
1408
1532
1765

# Operator module

In [34]:
import operator

In [35]:
numbers=[12,13,1,3,1,34,1344,124,233]
result=itertools.accumulate(numbers, operator.mul) #operator.mul for multiply
for i in result:
    print(i)

12
156
156
468
468
15912
21385728
2651830272
617876453376

In [36]:
result=itertools.accumulate(numbers, operator.add) #operator.add for addition
for i in result:
    print(i)

12
25
26
29
30
64
1408
1532
1765

# merging operations

In [37]:
import pandas as pd

In [62]:
df_orders=pd.read_excel(r'C:\Users\Futurense\Downloads\Sales Order.xlsx')
#by default it will take 1st sheet

In [43]:
df_orders

,Order ID,Unique ID,Customer,City,Quantity,Price,Total Sale Amount
0,NJ-2016-152156,NJ-2016-TT-107,Raymond Young,Troy,6,12.42,74.52
1,NJ-2016-138688,NJ-2016-PC-944,Helen Dean,Westfield,7,12.42,86.94
2,WA-2015-108966,WA-2015-TQ-107,Shirley Chavez,Seattle,2,16.32,32.64
3,NJ-2014-115812,NJ-2014-ZI-111,Brian Ryan,Westfield,1,12.42,12.42
4,NJ-2017-114412,NJ-2017-JR-537,Benjamin Willis,Westfield,3,17.83,53.49
...,...,...,...,...,...,...,...
4995,OR-2016-146374,OR-2016-NT-1000,Rachel Harris,Portland,10,12.42,124.20
4996,WA-2017-153871,WA-2017-YI-172,Earl White,Seattle,3,17.83,53.49
4997,WA-2015-103772,WA-2015-RA-513,Maria Romero,Seattle,7,12.42,86.94
4998,CT-2016-130225,CT-2016-ZX-360,Brandon Morales,Fairfield,5,53.35,266.75
4999,MA-2016-103674,MA-2016-ZD-503,Jason Patterson,Lowell,2,12.42,24.84

In [44]:
df_orders.head()

,Order ID,Unique ID,Customer,City,Quantity,Price,Total Sale Amount
0,NJ-2016-152156,NJ-2016-TT-107,Raymond Young,Troy,6,12.42,74.52
1,NJ-2016-138688,NJ-2016-PC-944,Helen Dean,Westfield,7,12.42,86.94
2,WA-2015-108966,WA-2015-TQ-107,Shirley Chavez,Seattle,2,16.32,32.64
3,NJ-2014-115812,NJ-2014-ZI-111,Brian Ryan,Westfield,1,12.42,12.42
4,NJ-2017-114412,NJ-2017-JR-537,Benjamin Willis,Westfield,3,17.83,53.49

In [63]:
df_returns=pd.read_excel(r'C:\Users\Futurense\Downloads\Sales Order.xlsx',sheet_name='Returns')
df_returns

,Order ID,Unique ID,Customer,City,State
0,NJ-2016-273214,NJ-ZKDFQ-821902,Raymond Young,Troy,New York
1,NJ-2016-271456,NJ-UTHRK-895117,Helen Dean,Westfield,New Jersey
2,WA-2015-451988,WA-ETBAQ-135442,Shirley Chavez,Seattle,Washington
3,NJ-2014-352961,NJ-EHGXM-601830,Brian Ryan,Westfield,New Jersey
4,NJ-2017-213231,NJ-CJFQS-287500,Benjamin Willis,Westfield,New Jersey
...,...,...,...,...,...
1995,OR-2014-443372,OR-MLTKR-791554,Kevin Garza,Portland,Oregon
1996,MA-2015-302053,MA-UZNIC-531357,Walter Kennedy,Lowell,Massachusetts
1997,NJ-2015-406754,NJ-JGMKR-831919,Shirley Morrison,Troy,New York
1998,CA-2017-214601,CA-RKJDJ-698676,Rachel Stanley,Los Angeles,California
1999,OR-2015-206233,OR-KUARX-249729,Teresa Fisher,Portland,Oregon

In [46]:
#records are unique and no null values in primary key
#
inner_join=pd.merge(left=df_orders,
                   right=df_returns,
                   left_on='Order ID',
                   right_on='Order ID',
                   how='inner')
inner_join

,Order ID,Unique ID_x,Customer_x,City_x,Quantity,Price,Total Sale Amount,Unique ID_y,Customer_y,City_y,State
0,WA-2016-117590,NJ-TEXWY-11752,Judy Sanchez,Seattle,7,53.35,373.45,NJ-TEXWY-11752,Judy Sanchez,Seattle,Washington
1,WA-2015-117415,NJ-QDWAV-21173,Harold Hunter,Seattle,4,12.42,49.68,NJ-QDWAV-21173,Harold Hunter,Seattle,Washington
2,MA-2017-120999,WA-JJEKO-18817,Lori Shaw,Lowell,7,16.32,114.24,WA-JJEKO-18817,Lori Shaw,Lowell,Massachusetts
3,NJ-2016-101343,NJ-MJQGV-20387,Sandra Hicks,Troy,1,53.35,53.35,NJ-MJQGV-20387,Sandra Hicks,Troy,New York
4,MA-2017-139619,NJ-SDISO-30581,Roger Gomez,Lowell,7,16.32,114.24,NJ-SDISO-30581,Roger Gomez,Lowell,Massachusetts
...,...,...,...,...,...,...,...,...,...,...,...
84,OR-2016-160528,CT-AUHPF-47296,Henry Day,Portland,8,12.42,99.36,CT-AUHPF-47296,Henry Day,Portland,Oregon
85,WA-2017-106859,NJ-QZWWQ-32114,Jennifer Adams,Seattle,7,53.35,373.45,NJ-QZWWQ-32114,Jennifer Adams,Seattle,Washington
86,WA-2014-136399,NV-RMZCI-41025,Stephanie Wallace,Seattle,2,17.83,35.66,NV-RMZCI-41025,Stephanie Wallace,Seattle,Washington
87,MA-2017-105921,NJ-OQOLC-37747,Joshua Diaz,Lowell,2,17.83,35.66,NJ-OQOLC-37747,Joseph Bishop,Lowell,Massachusetts
88,CT-2014-137274,MA-PQATH-24777,Brandon Morales,Fairfield,1,53.35,53.35,MA-PQATH-24777,Debra Gutierrez,Fairfield,Connecticut

In [47]:
inner_join.shape

(89, 11)

In [48]:
inner_join2=pd.merge(left=df_orders,
                   right=df_returns,
                   on='Order ID',
                   )
inner_join2

,Order ID,Unique ID_x,Customer_x,City_x,Quantity,Price,Total Sale Amount,Unique ID_y,Customer_y,City_y,State
0,WA-2016-117590,NJ-TEXWY-11752,Judy Sanchez,Seattle,7,53.35,373.45,NJ-TEXWY-11752,Judy Sanchez,Seattle,Washington
1,WA-2015-117415,NJ-QDWAV-21173,Harold Hunter,Seattle,4,12.42,49.68,NJ-QDWAV-21173,Harold Hunter,Seattle,Washington
2,MA-2017-120999,WA-JJEKO-18817,Lori Shaw,Lowell,7,16.32,114.24,WA-JJEKO-18817,Lori Shaw,Lowell,Massachusetts
3,NJ-2016-101343,NJ-MJQGV-20387,Sandra Hicks,Troy,1,53.35,53.35,NJ-MJQGV-20387,Sandra Hicks,Troy,New York
4,MA-2017-139619,NJ-SDISO-30581,Roger Gomez,Lowell,7,16.32,114.24,NJ-SDISO-30581,Roger Gomez,Lowell,Massachusetts
...,...,...,...,...,...,...,...,...,...,...,...
84,OR-2016-160528,CT-AUHPF-47296,Henry Day,Portland,8,12.42,99.36,CT-AUHPF-47296,Henry Day,Portland,Oregon
85,WA-2017-106859,NJ-QZWWQ-32114,Jennifer Adams,Seattle,7,53.35,373.45,NJ-QZWWQ-32114,Jennifer Adams,Seattle,Washington
86,WA-2014-136399,NV-RMZCI-41025,Stephanie Wallace,Seattle,2,17.83,35.66,NV-RMZCI-41025,Stephanie Wallace,Seattle,Washington
87,MA-2017-105921,NJ-OQOLC-37747,Joshua Diaz,Lowell,2,17.83,35.66,NJ-OQOLC-37747,Joseph Bishop,Lowell,Massachusetts
88,CT-2014-137274,MA-PQATH-24777,Brandon Morales,Fairfield,1,53.35,53.35,MA-PQATH-24777,Debra Gutierrez,Fairfield,Connecticut

In [49]:
inner_join2.shape

(89, 11)

In [ ]:
#suffixed by _x' means then the records are part of left table,
#suffixed by'_y' means then the records are part of right table

In [50]:
inner_join3=pd.merge(left=df_orders,
                   right=df_returns,
                   left_on='Order ID',
                   right_on='Order ID',
                   how='inner',
                   suffixes=('_Orders','_Returns'))
inner_join3

,Order ID,Unique ID_Orders,Customer_Orders,City_Orders,Quantity,Price,Total Sale Amount,Unique ID_Returns,Customer_Returns,City_Returns,State
0,WA-2016-117590,NJ-TEXWY-11752,Judy Sanchez,Seattle,7,53.35,373.45,NJ-TEXWY-11752,Judy Sanchez,Seattle,Washington
1,WA-2015-117415,NJ-QDWAV-21173,Harold Hunter,Seattle,4,12.42,49.68,NJ-QDWAV-21173,Harold Hunter,Seattle,Washington
2,MA-2017-120999,WA-JJEKO-18817,Lori Shaw,Lowell,7,16.32,114.24,WA-JJEKO-18817,Lori Shaw,Lowell,Massachusetts
3,NJ-2016-101343,NJ-MJQGV-20387,Sandra Hicks,Troy,1,53.35,53.35,NJ-MJQGV-20387,Sandra Hicks,Troy,New York
4,MA-2017-139619,NJ-SDISO-30581,Roger Gomez,Lowell,7,16.32,114.24,NJ-SDISO-30581,Roger Gomez,Lowell,Massachusetts
...,...,...,...,...,...,...,...,...,...,...,...
84,OR-2016-160528,CT-AUHPF-47296,Henry Day,Portland,8,12.42,99.36,CT-AUHPF-47296,Henry Day,Portland,Oregon
85,WA-2017-106859,NJ-QZWWQ-32114,Jennifer Adams,Seattle,7,53.35,373.45,NJ-QZWWQ-32114,Jennifer Adams,Seattle,Washington
86,WA-2014-136399,NV-RMZCI-41025,Stephanie Wallace,Seattle,2,17.83,35.66,NV-RMZCI-41025,Stephanie Wallace,Seattle,Washington
87,MA-2017-105921,NJ-OQOLC-37747,Joshua Diaz,Lowell,2,17.83,35.66,NJ-OQOLC-37747,Joseph Bishop,Lowell,Massachusetts
88,CT-2014-137274,MA-PQATH-24777,Brandon Morales,Fairfield,1,53.35,53.35,MA-PQATH-24777,Debra Gutierrez,Fairfield,Connecticut

In [51]:
df_orders['Order ID'].isin(df_returns['Order ID']).value_counts()

False    4911
True       89
Name: Order ID, dtype: int64

In [53]:
#renaming the column name
df_returns.rename(columns={df_returns.columns[0]:'Invoice ID'},inplace=True)
df_returns.head()

       Invoice ID        Unique ID         Customer       City       State
0  NJ-2016-273214  NJ-ZKDFQ-821902    Raymond Young       Troy    New York
1  NJ-2016-271456  NJ-UTHRK-895117       Helen Dean  Westfield  New Jersey
2  WA-2015-451988  WA-ETBAQ-135442   Shirley Chavez    Seattle  Washington
3  NJ-2014-352961  NJ-EHGXM-601830       Brian Ryan  Westfield  New Jersey
4  NJ-2017-213231  NJ-CJFQS-287500  Benjamin Willis  Westfield  New Jersey

In [54]:
inner_join_again=pd.merge(df_orders, df_returns,
                         left_on=['Order ID','City'],
                         right_on=['Invoice ID','City'],
                         indicator=True)
inner_join_again

,Order ID,Unique ID_x,Customer_x,City,Quantity,Price,Total Sale Amount,Invoice ID,Unique ID_y,Customer_y,State,_merge
0,WA-2016-117590,NJ-TEXWY-11752,Judy Sanchez,Seattle,7,53.35,373.45,WA-2016-117590,NJ-TEXWY-11752,Judy Sanchez,Washington,both
1,WA-2015-117415,NJ-QDWAV-21173,Harold Hunter,Seattle,4,12.42,49.68,WA-2015-117415,NJ-QDWAV-21173,Harold Hunter,Washington,both
2,MA-2017-120999,WA-JJEKO-18817,Lori Shaw,Lowell,7,16.32,114.24,MA-2017-120999,WA-JJEKO-18817,Lori Shaw,Massachusetts,both
3,NJ-2016-101343,NJ-MJQGV-20387,Sandra Hicks,Troy,1,53.35,53.35,NJ-2016-101343,NJ-MJQGV-20387,Sandra Hicks,New York,both
4,MA-2017-139619,NJ-SDISO-30581,Roger Gomez,Lowell,7,16.32,114.24,MA-2017-139619,NJ-SDISO-30581,Roger Gomez,Massachusetts,both
...,...,...,...,...,...,...,...,...,...,...,...,...
84,OR-2016-160528,CT-AUHPF-47296,Henry Day,Portland,8,12.42,99.36,OR-2016-160528,CT-AUHPF-47296,Henry Day,Oregon,both
85,WA-2017-106859,NJ-QZWWQ-32114,Jennifer Adams,Seattle,7,53.35,373.45,WA-2017-106859,NJ-QZWWQ-32114,Jennifer Adams,Washington,both
86,WA-2014-136399,NV-RMZCI-41025,Stephanie Wallace,Seattle,2,17.83,35.66,WA-2014-136399,NV-RMZCI-41025,Stephanie Wallace,Washington,both
87,MA-2017-105921,NJ-OQOLC-37747,Joshua Diaz,Lowell,2,17.83,35.66,MA-2017-105921,NJ-OQOLC-37747,Joseph Bishop,Massachusetts,both
88,CT-2014-137274,MA-PQATH-24777,Brandon Morales,Fairfield,1,53.35,53.35,CT-2014-137274,MA-PQATH-24777,Debra Gutierrez,Connecticut,both

In [57]:
df_returns

,Invoice ID,Unique ID,Customer,City,State
0,NJ-2016-273214,NJ-ZKDFQ-821902,Raymond Young,Troy,New York
1,NJ-2016-271456,NJ-UTHRK-895117,Helen Dean,Westfield,New Jersey
2,WA-2015-451988,WA-ETBAQ-135442,Shirley Chavez,Seattle,Washington
3,NJ-2014-352961,NJ-EHGXM-601830,Brian Ryan,Westfield,New Jersey
4,NJ-2017-213231,NJ-CJFQS-287500,Benjamin Willis,Westfield,New Jersey
...,...,...,...,...,...
1995,OR-2014-443372,OR-MLTKR-791554,Kevin Garza,Portland,Oregon
1996,MA-2015-302053,MA-UZNIC-531357,Walter Kennedy,Lowell,Massachusetts
1997,NJ-2015-406754,NJ-JGMKR-831919,Shirley Morrison,Troy,New York
1998,CA-2017-214601,CA-RKJDJ-698676,Rachel Stanley,Los Angeles,California
1999,OR-2015-206233,OR-KUARX-249729,Teresa Fisher,Portland,Oregon

In [64]:
left_join=pd.merge(left=df_orders,
                  right=df_returns,
                  on='Order ID',
                  how='left',
                  indicator=True)
left_join.head()

,Order ID,Unique ID_x,Customer_x,City_x,Quantity,Price,Total Sale Amount,Unique ID_y,Customer_y,City_y,State,_merge
0,NJ-2016-152156,NJ-2016-TT-107,Raymond Young,Troy,6,12.42,74.52,NaN,NaN,NaN,NaN,left_only
1,NJ-2016-138688,NJ-2016-PC-944,Helen Dean,Westfield,7,12.42,86.94,NaN,NaN,NaN,NaN,left_only
2,WA-2015-108966,WA-2015-TQ-107,Shirley Chavez,Seattle,2,16.32,32.64,NaN,NaN,NaN,NaN,left_only
3,NJ-2014-115812,NJ-2014-ZI-111,Brian Ryan,Westfield,1,12.42,12.42,NaN,NaN,NaN,NaN,left_only
4,NJ-2017-114412,NJ-2017-JR-537,Benjamin Willis,Westfield,3,17.83,53.49,NaN,NaN,NaN,NaN,left_only

In [65]:
left_join.shape

(5000, 12)

# Right Join

In [66]:
right_join=pd.merge(left=df_orders,
                  right=df_returns,
                  on='Order ID',
                  how='right',
                  indicator=True)
right_join.shape

(2000, 12)

In [67]:
right_join.head()

,Order ID,Unique ID_x,Customer_x,City_x,Quantity,Price,Total Sale Amount,Unique ID_y,Customer_y,City_y,State,_merge
0,NJ-2016-273214,NaN,NaN,NaN,NaN,NaN,NaN,NJ-ZKDFQ-821902,Raymond Young,Troy,New York,right_only
1,NJ-2016-271456,NaN,NaN,NaN,NaN,NaN,NaN,NJ-UTHRK-895117,Helen Dean,Westfield,New Jersey,right_only
2,WA-2015-451988,NaN,NaN,NaN,NaN,NaN,NaN,WA-ETBAQ-135442,Shirley Chavez,Seattle,Washington,right_only
3,NJ-2014-352961,NaN,NaN,NaN,NaN,NaN,NaN,NJ-EHGXM-601830,Brian Ryan,Westfield,New Jersey,right_only
4,NJ-2017-213231,NaN,NaN,NaN,NaN,NaN,NaN,NJ-CJFQS-287500,Benjamin Willis,Westfield,New Jersey,right_only

In [70]:
right_join._merge.value_counts()

right_only    1911
both            89
left_only        0
Name: _merge, dtype: int64

# Full Join

In [71]:
full_join=pd.merge(df_orders, df_returns, on='Order ID',how='outer',indicator=True)
print(full_join.head())
print(full_join.shape)

         Order ID     Unique ID_x       Customer_x     City_x  Quantity  \
0  NJ-2016-152156  NJ-2016-TT-107    Raymond Young       Troy       6.0
1  NJ-2016-138688  NJ-2016-PC-944       Helen Dean  Westfield       7.0
2  WA-2015-108966  WA-2015-TQ-107   Shirley Chavez    Seattle       2.0
3  NJ-2014-115812  NJ-2014-ZI-111       Brian Ryan  Westfield       1.0
4  NJ-2017-114412  NJ-2017-JR-537  Benjamin Willis  Westfield       3.0

   Price  Total Sale Amount Unique ID_y Customer_y City_y State     _merge
0  12.42              74.52         NaN        NaN    NaN   NaN  left_only
1  12.42              86.94         NaN        NaN    NaN   NaN  left_only
2  16.32              32.64         NaN        NaN    NaN   NaN  left_only
3  12.42              12.42         NaN        NaN    NaN   NaN  left_only
4  17.83              53.49         NaN        NaN    NaN   NaN  left_only
(6911, 12)

# JSON: JavaScript Object Notation

In [ ]:
people_string=''

In [1]:
import json

In [79]:
people_string = '''
{"people":[{"name":"Chirantan Lonkar",
            "phone":"+918879781973",
            "emails":["chirantan.lonkar@mileseducation.com","chirantan.lonkar@futurense.com"],
            "has_license": false
 
},
{
            "name":"Babloo Tripathi",
            "phone":"+918879781902",
            "emails":null,
            "has_license": false
 
}
 
]
 
}
 
'''

In [80]:
type(people_string)

str

In [81]:
#JSON to python object
data=json.loads(people_string) #loads stands for load a string
print(data)

{'people': [{'name': 'Chirantan Lonkar', 'phone': '+918879781973', 'emails': ['chirantan.lonkar@mileseducation.com', 'chirantan.lonkar@futurense.com'], 'has_license': False}, {'name': 'Babloo Tripathi', 'phone': '+918879781902', 'emails': None, 'has_license': False}]}

In [ ]:
#but this is unreadable and looks like a dictionary

In [76]:
# conversion in python goes like
 
# json object : converts dictionary
# json arrays : python lists
# string : python string
# int:int
# true : True
# false: False
# null : python None values

In [77]:
type(data)

dict

In [78]:
type(data['people'])

list

In [82]:
for person in data['people']:
    print(person)

#null in json trated as None in python

{'name': 'Chirantan Lonkar', 'phone': '+918879781973', 'emails': ['chirantan.lonkar@mileseducation.com', 'chirantan.lonkar@futurense.com'], 'has_license': False}
{'name': 'Babloo Tripathi', 'phone': '+918879781902', 'emails': None, 'has_license': False}

In [83]:
for person in data['people']:
    print(person['name'])

Chirantan Lonkar
Babloo Tripathi

In [ ]:
#let us dump a python object into a json string

In [ ]:
# let us dump a python object into a json string
# use json.dumps
 
# we want to remove the phone numbers from each person  and convert it back to a json string
# remove phone numberkey and value

In [84]:
#remove a key in the original dictionary
for person in data['people']:
    del person['phone']

In [85]:
data

{'people': [{'name': 'Chirantan Lonkar',
   'emails': ['chirantan.lonkar@mileseducation.com',
    'chirantan.lonkar@futurense.com'],
   'has_license': False},
  {'name': 'Babloo Tripathi', 'emails': None, 'has_license': False}]}

In [86]:
#python object to JSON string
new_string=json.dumps(data)
new_string
# now we can see , the output has new json string that does not contain phone number

'{"people": [{"name": "Chirantan Lonkar", "emails": ["chirantan.lonkar@mileseducation.com", "chirantan.lonkar@futurense.com"], "has_license": false}, {"name": "Babloo Tripathi", "emails": null, "has_license": false}]}'

In [ ]:
#we have a file states.json

In [2]:
#load this josn into python object
#Loads method loads a string

with open(r'C:\Users\Futurense\Downloads\states.json','r' )as f:
    data=json.load(f)

In [3]:
data

{'states': [{'name': 'Alabama',
   'abbreviation': 'AL',
   'area_codes': ['205', '251', '256', '334', '938']},
  {'name': 'Alaska', 'abbreviation': 'AK', 'area_codes': ['907']},
  {'name': 'Arizona',
   'abbreviation': 'AZ',
   'area_codes': ['480', '520', '602', '623', '928']},
  {'name': 'Arkansas',
   'abbreviation': 'AR',
   'area_codes': ['479', '501', '870']},
  {'name': 'California',
   'abbreviation': 'CA',
   'area_codes': ['209',
    '213',
    '310',
    '323',
    '408',
    '415',
    '424',
    '442',
    '510',
    '530',
    '559',
    '562',
    '619',
    '626',
    '628',
    '650',
    '657',
    '661',
    '669',
    '707',
    '714',
    '747',
    '760',
    '805',
    '818',
    '831',
    '858',
    '909',
    '916',
    '925',
    '949',
    '951']},
  {'name': 'Colorado',
   'abbreviation': 'CO',
   'area_codes': ['303', '719', '720', '970']},
  {'name': 'Connecticut',
   'abbreviation': 'CT',
   'area_codes': ['203', '475', '860', '959']},
  {'name': 'Delaware', 'abbreviation': 'DE', 'area_codes': ['302']},
  {'name': 'Florida',
   'abbreviation': 'FL',
   'area_codes': ['239',
    '305',
    '321',
    '352',
    '386',
    '407',
    '561',
    '727',
    '754',
    '772',
    '786',
    '813',
    '850',
    '863',
    '904',
    '941',
    '954']},
  {'name': 'Georgia',
   'abbreviation': 'GA',
   'area_codes': ['229',
    '404',
    '470',
    '478',
    '678',
    '706',
    '762',
    '770',
    '912']},
  {'name': 'Hawaii', 'abbreviation': 'HI', 'area_codes': ['808']},
  {'name': 'Idaho', 'abbreviation': 'ID', 'area_codes': ['208']},
  {'name': 'Illinois',
   'abbreviation': 'IL',
   'area_codes': ['217',
    '224',
    '309',
    '312',
    '331',
    '618',
    '630',
    '708',
    '773',
    '779',
    '815',
    '847',
    '872']},
  {'name': 'Indiana',
   'abbreviation': 'IN',
   'area_codes': ['219', '260', '317', '463', '574', '765', '812', '930']},
  {'name': 'Iowa',
   'abbreviation': 'IA',
   'area_codes': ['319', '515', '563', '641', '712']},
  {'name': 'Kansas',
   'abbreviation': 'KS',
   'area_codes': ['316', '620', '785', '913']},
  {'name': 'Kentucky',
   'abbreviation': 'KY',
   'area_codes': ['270', '364', '502', '606', '859']},
  {'name': 'Louisiana',
   'abbreviation': 'LA',
   'area_codes': ['225', '318', '337', '504', '985']},
  {'name': 'Maine', 'abbreviation': 'ME', 'area_codes': ['207']},
  {'name': 'Maryland',
   'abbreviation': 'MD',
   'area_codes': ['240', '301', '410', '443', '667']},
  {'name': 'Massachusetts',
   'abbreviation': 'MA',
   'area_codes': ['339',
    '351',
    '413',
    '508',
    '617',
    '774',
    '781',
    '857',
    '978']},
  {'name': 'Michigan',
   'abbreviation': 'MI',
   'area_codes': ['231',
    '248',
    '269',
    '313',
    '517',
    '586',
    '616',
    '734',
    '810',
    '906',
    '947',
    '989']},
  {'name': 'Minnesota',
   'abbreviation': 'MN',
   'area_codes': ['218', '320', '507', '612', '651', '763', '952']},
  {'name': 'Mississippi',
   'abbreviation': 'MS',
   'area_codes': ['228', '601', '662', '769']},
  {'name': 'Missouri',
   'abbreviation': 'MO',
   'area_codes': ['314', '417', '573', '636', '660', '816']},
  {'name': 'Montana', 'abbreviation': 'MT', 'area_codes': ['406']},
  {'name': 'Nebraska',
   'abbreviation': 'NE',
   'area_codes': ['308', '402', '531']},
  {'name': 'Nevada',
   'abbreviation': 'NV',
   'area_codes': ['702', '725', '775']},
  {'name': 'New Hampshire', 'abbreviation': 'NH', 'area_codes': ['603']},
  {'name': 'New Jersey',
   'abbreviation': 'NJ',
   'area_codes': ['201',
    '551',
    '609',
    '732',
    '848',
    '856',
    '862',
    '908',
    '973']},
  {'name': 'New Mexico', 'abbreviation': 'NM', 'area_codes': ['505', '575']},
  {'name': 'New York',
   'abbreviation': 'NY',
   'area_codes': ['212',
    '315',
    '332',
    '347',
    '516',
    '518',
    '585',
    '607',
    '631',
    '646',
    '680',
    '716',
    '718',
    '845',
    '914',
    '917',
    '929',
    '934']},
  {'name': 'North Carolina',
   'abbreviation': 'NC',
   'area_codes': ['252',
    '336',
    '704',
    '743',
    '828',
    '910',
    '919',
    '980',
    '984']},
  {'name': 'North Dakota', 'abbreviation': 'ND', 'area_codes': ['701']},
  {'name': 'Ohio',
   'abbreviation': 'OH',
   'area_codes': ['216',
    '220',
    '234',
    '330',
    '380',
    '419',
    '440',
    '513',
    '567',
    '614',
    '740',
    '937']},
  {'name': 'Oklahoma',
   'abbreviation': 'OK',
   'area_codes': ['405', '539', '580', '918']},
  {'name': 'Oregon',
   'abbreviation': 'OR',
   'area_codes': ['458', '503', '541', '971']},
  {'name': 'Pennsylvania',
   'abbreviation': 'PA',
   'area_codes': ['215',
    '267',
    '272',
    '412',
    '484',
    '570',
    '610',
    '717',
    '724',
    '814',
    '878']},
  {'name': 'Rhode Island', 'abbreviation': 'RI', 'area_codes': ['401']},
  {'name': 'South Carolina',
   'abbreviation': 'SC',
   'area_codes': ['803', '843', '854', '864']},
  {'name': 'South Dakota', 'abbreviation': 'SD', 'area_codes': ['605']},
  {'name': 'Tennessee',
   'abbreviation': 'TN',
   'area_codes': ['423', '615', '629', '731', '865', '901', '931']},
  {'name': 'Texas',
   'abbreviation': 'TX',
   'area_codes': ['210',
    '214',
    '254',
    '281',
    '325',
    '346',
    '361',
    '409',
    '430',
    '432',
    '469',
    '512',
    '682',
    '713',
    '737',
    '806',
    '817',
    '830',
    '832',
    '903',
    '915',
    '936',
    '940',
    '956',
    '972',
    '979']},
  {'name': 'Utah', 'abbreviation': 'UT', 'area_codes': ['385', '435', '801']},
  {'name': 'Vermont', 'abbreviation': 'VT', 'area_codes': ['802']},
  {'name': 'Virginia',
   'abbreviation': 'VA',
   'area_codes': ['276', '434', '540', '571', '703', '757', '804']},
  {'name': 'Washington',
   'abbreviation': 'WA',
   'area_codes': ['206', '253', '360', '425', '509']},
  {'name': 'West Virginia',
   'abbreviation': 'WV',
   'area_codes': ['304', '681']},
  {'name': 'Wisconsin',
   'abbreviation': 'WI',
   'area_codes': ['262', '414', '534', '608', '715', '920']},
  {'name': 'Wyoming', 'abbreviation': 'WY', 'area_codes': ['307']}]}

In [5]:
for state in data['states']:
    print(state)

{'name': 'Alabama', 'abbreviation': 'AL', 'area_codes': ['205', '251', '256', '334', '938']}
{'name': 'Alaska', 'abbreviation': 'AK', 'area_codes': ['907']}
{'name': 'Arizona', 'abbreviation': 'AZ', 'area_codes': ['480', '520', '602', '623', '928']}
{'name': 'Arkansas', 'abbreviation': 'AR', 'area_codes': ['479', '501', '870']}
{'name': 'California', 'abbreviation': 'CA', 'area_codes': ['209', '213', '310', '323', '408', '415', '424', '442', '510', '530', '559', '562', '619', '626', '628', '650', '657', '661', '669', '707', '714', '747', '760', '805', '818', '831', '858', '909', '916', '925', '949', '951']}
{'name': 'Colorado', 'abbreviation': 'CO', 'area_codes': ['303', '719', '720', '970']}
{'name': 'Connecticut', 'abbreviation': 'CT', 'area_codes': ['203', '475', '860', '959']}
{'name': 'Delaware', 'abbreviation': 'DE', 'area_codes': ['302']}
{'name': 'Florida', 'abbreviation': 'FL', 'area_codes': ['239', '305', '321', '352', '386', '407', '561', '727', '754', '772', '786', '813', '850', '863', '904', '941', '954']}
{'name': 'Georgia', 'abbreviation': 'GA', 'area_codes': ['229', '404', '470', '478', '678', '706', '762', '770', '912']}
{'name': 'Hawaii', 'abbreviation': 'HI', 'area_codes': ['808']}
{'name': 'Idaho', 'abbreviation': 'ID', 'area_codes': ['208']}
{'name': 'Illinois', 'abbreviation': 'IL', 'area_codes': ['217', '224', '309', '312', '331', '618', '630', '708', '773', '779', '815', '847', '872']}
{'name': 'Indiana', 'abbreviation': 'IN', 'area_codes': ['219', '260', '317', '463', '574', '765', '812', '930']}
{'name': 'Iowa', 'abbreviation': 'IA', 'area_codes': ['319', '515', '563', '641', '712']}
{'name': 'Kansas', 'abbreviation': 'KS', 'area_codes': ['316', '620', '785', '913']}
{'name': 'Kentucky', 'abbreviation': 'KY', 'area_codes': ['270', '364', '502', '606', '859']}
{'name': 'Louisiana', 'abbreviation': 'LA', 'area_codes': ['225', '318', '337', '504', '985']}
{'name': 'Maine', 'abbreviation': 'ME', 'area_codes': ['207']}
{'name': 'Maryland', 'abbreviation': 'MD', 'area_codes': ['240', '301', '410', '443', '667']}
{'name': 'Massachusetts', 'abbreviation': 'MA', 'area_codes': ['339', '351', '413', '508', '617', '774', '781', '857', '978']}
{'name': 'Michigan', 'abbreviation': 'MI', 'area_codes': ['231', '248', '269', '313', '517', '586', '616', '734', '810', '906', '947', '989']}
{'name': 'Minnesota', 'abbreviation': 'MN', 'area_codes': ['218', '320', '507', '612', '651', '763', '952']}
{'name': 'Mississippi', 'abbreviation': 'MS', 'area_codes': ['228', '601', '662', '769']}
{'name': 'Missouri', 'abbreviation': 'MO', 'area_codes': ['314', '417', '573', '636', '660', '816']}
{'name': 'Montana', 'abbreviation': 'MT', 'area_codes': ['406']}
{'name': 'Nebraska', 'abbreviation': 'NE', 'area_codes': ['308', '402', '531']}
{'name': 'Nevada', 'abbreviation': 'NV', 'area_codes': ['702', '725', '775']}
{'name': 'New Hampshire', 'abbreviation': 'NH', 'area_codes': ['603']}
{'name': 'New Jersey', 'abbreviation': 'NJ', 'area_codes': ['201', '551', '609', '732', '848', '856', '862', '908', '973']}
{'name': 'New Mexico', 'abbreviation': 'NM', 'area_codes': ['505', '575']}
{'name': 'New York', 'abbreviation': 'NY', 'area_codes': ['212', '315', '332', '347', '516', '518', '585', '607', '631', '646', '680', '716', '718', '845', '914', '917', '929', '934']}
{'name': 'North Carolina', 'abbreviation': 'NC', 'area_codes': ['252', '336', '704', '743', '828', '910', '919', '980', '984']}
{'name': 'North Dakota', 'abbreviation': 'ND', 'area_codes': ['701']}
{'name': 'Ohio', 'abbreviation': 'OH', 'area_codes': ['216', '220', '234', '330', '380', '419', '440', '513', '567', '614', '740', '937']}
{'name': 'Oklahoma', 'abbreviation': 'OK', 'area_codes': ['405', '539', '580', '918']}
{'name': 'Oregon', 'abbreviation': 'OR', 'area_codes': ['458', '503', '541', '971']}
{'name': 'Pennsylvania', 'abbreviation': 'PA', 'area_codes': ['215', '267', '272', '412', '484', '570', '610', '717', '724', '814', '878']}
{'name': 'Rhode Island', 'abbreviation': 'RI', 'area_codes': ['401']}
{'name': 'South Carolina', 'abbreviation': 'SC', 'area_codes': ['803', '843', '854', '864']}
{'name': 'South Dakota', 'abbreviation': 'SD', 'area_codes': ['605']}
{'name': 'Tennessee', 'abbreviation': 'TN', 'area_codes': ['423', '615', '629', '731', '865', '901', '931']}
{'name': 'Texas', 'abbreviation': 'TX', 'area_codes': ['210', '214', '254', '281', '325', '346', '361', '409', '430', '432', '469', '512', '682', '713', '737', '806', '817', '830', '832', '903', '915', '936', '940', '956', '972', '979']}
{'name': 'Utah', 'abbreviation': 'UT', 'area_codes': ['385', '435', '801']}
{'name': 'Vermont', 'abbreviation': 'VT', 'area_codes': ['802']}
{'name': 'Virginia', 'abbreviation': 'VA', 'area_codes': ['276', '434', '540', '571', '703', '757', '804']}
{'name': 'Washington', 'abbreviation': 'WA', 'area_codes': ['206', '253', '360', '425', '509']}
{'name': 'West Virginia', 'abbreviation': 'WV', 'area_codes': ['304', '681']}
{'name': 'Wisconsin', 'abbreviation': 'WI', 'area_codes': ['262', '414', '534', '608', '715', '920']}
{'name': 'Wyoming', 'abbreviation': 'WY', 'area_codes': ['307']}

In [6]:
for i in data['states']:
    print(i['name'],i['abbreviation'])

Alabama AL
Alaska AK
Arizona AZ
Arkansas AR
California CA
Colorado CO
Connecticut CT
Delaware DE
Florida FL
Georgia GA
Hawaii HI
Idaho ID
Illinois IL
Indiana IN
Iowa IA
Kansas KS
Kentucky KY
Louisiana LA
Maine ME
Maryland MD
Massachusetts MA
Michigan MI
Minnesota MN
Mississippi MS
Missouri MO
Montana MT
Nebraska NE
Nevada NV
New Hampshire NH
New Jersey NJ
New Mexico NM
New York NY
North Carolina NC
North Dakota ND
Ohio OH
Oklahoma OK
Oregon OR
Pennsylvania PA
Rhode Island RI
South Carolina SC
South Dakota SD
Tennessee TN
Texas TX
Utah UT
Vermont VT
Virginia VA
Washington WA
West Virginia WV
Wisconsin WI
Wyoming WY

In [8]:
for i in data['states']:
    del i['area_codes']

In [9]:
with open('new_states.json','w') as f:
    json.dump(data, f, indent=2)

In [1]:
with open('new_states.json','r') as f:
    data = json.load(f)

NameError: name 'json' is not defined

In [15]:
data

{'states': [{'name': 'Alabama', 'abbreviation': 'AL'},
  {'name': 'Alaska', 'abbreviation': 'AK'},
  {'name': 'Arizona', 'abbreviation': 'AZ'},
  {'name': 'Arkansas', 'abbreviation': 'AR'},
  {'name': 'California', 'abbreviation': 'CA'},
  {'name': 'Colorado', 'abbreviation': 'CO'},
  {'name': 'Connecticut', 'abbreviation': 'CT'},
  {'name': 'Delaware', 'abbreviation': 'DE'},
  {'name': 'Florida', 'abbreviation': 'FL'},
  {'name': 'Georgia', 'abbreviation': 'GA'},
  {'name': 'Hawaii', 'abbreviation': 'HI'},
  {'name': 'Idaho', 'abbreviation': 'ID'},
  {'name': 'Illinois', 'abbreviation': 'IL'},
  {'name': 'Indiana', 'abbreviation': 'IN'},
  {'name': 'Iowa', 'abbreviation': 'IA'},
  {'name': 'Kansas', 'abbreviation': 'KS'},
  {'name': 'Kentucky', 'abbreviation': 'KY'},
  {'name': 'Louisiana', 'abbreviation': 'LA'},
  {'name': 'Maine', 'abbreviation': 'ME'},
  {'name': 'Maryland', 'abbreviation': 'MD'},
  {'name': 'Massachusetts', 'abbreviation': 'MA'},
  {'name': 'Michigan', 'abbreviation': 'MI'},
  {'name': 'Minnesota', 'abbreviation': 'MN'},
  {'name': 'Mississippi', 'abbreviation': 'MS'},
  {'name': 'Missouri', 'abbreviation': 'MO'},
  {'name': 'Montana', 'abbreviation': 'MT'},
  {'name': 'Nebraska', 'abbreviation': 'NE'},
  {'name': 'Nevada', 'abbreviation': 'NV'},
  {'name': 'New Hampshire', 'abbreviation': 'NH'},
  {'name': 'New Jersey', 'abbreviation': 'NJ'},
  {'name': 'New Mexico', 'abbreviation': 'NM'},
  {'name': 'New York', 'abbreviation': 'NY'},
  {'name': 'North Carolina', 'abbreviation': 'NC'},
  {'name': 'North Dakota', 'abbreviation': 'ND'},
  {'name': 'Ohio', 'abbreviation': 'OH'},
  {'name': 'Oklahoma', 'abbreviation': 'OK'},
  {'name': 'Oregon', 'abbreviation': 'OR'},
  {'name': 'Pennsylvania', 'abbreviation': 'PA'},
  {'name': 'Rhode Island', 'abbreviation': 'RI'},
  {'name': 'South Carolina', 'abbreviation': 'SC'},
  {'name': 'South Dakota', 'abbreviation': 'SD'},
  {'name': 'Tennessee', 'abbreviation': 'TN'},
  {'name': 'Texas', 'abbreviation': 'TX'},
  {'name': 'Utah', 'abbreviation': 'UT'},
  {'name': 'Vermont', 'abbreviation': 'VT'},
  {'name': 'Virginia', 'abbreviation': 'VA'},
  {'name': 'Washington', 'abbreviation': 'WA'},
  {'name': 'West Virginia', 'abbreviation': 'WV'},
  {'name': 'Wisconsin', 'abbreviation': 'WI'},
  {'name': 'Wyoming', 'abbreviation': 'WY'}]}

# Lambda functions

In [17]:
sum1=lambda x,y: x+y
print('The sum of the given two numbers is: ',sum1(2,3))

The sum of the given two numbers is:  5

In [18]:
prod=lambda x,y,z: x*y*z
print('The prod of 3 numbers: ',prod(1,2,3))

The prod of 3 numbers:  6

In [19]:
list_a=[('eggs',5.25),('peaches',9.78),('honey',1.10),('carrots',2.45)]
list_a.sort(key=lambda x: x[1])

print(list_a)

[('honey', 1.1), ('carrots', 2.45), ('eggs', 5.25), ('peaches', 9.78)]

In [21]:
#sorting list of dictionaries using LAMBDA

list_a=[{
    'make':'Ford',
    'model':'Focus',
    'year':2013
},
    {
        'make':'Tesla',
    'model':'X',
    'year':1999
    },
    {
        'make':'Mercedes',
    'model':'Maybach',
    'year':2009
    }
]
list_b=sorted(list_a, key=lambda x:x['year'])
print(list_b)
#x is the entire dictionary

[{'make': 'Tesla', 'model': 'X', 'year': 1999}, {'make': 'Mercedes', 'model': 'Maybach', 'year': 2009}, {'make': 'Ford', 'model': 'Focus', 'year': 2013}]

In [24]:
#filter function using lambda function
list_a=[1,2,3,4,5,6,7,8,9,10,11,12,13]
list_b=list(filter(lambda x: x%2==0, list_a))
print(list_b)

[2, 4, 6, 8, 10, 12]

In [27]:
list_c=list(map(lambda x: x**2,list_a))
print(list_c)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169]

In [29]:
name_j=lambda x: True if x.startswith('J') else False
print(name_j('Jatin'))

True

In [30]:
print(name_j('Raj'))

False

In [31]:
import datetime

In [32]:
now=datetime.datetime.now()

In [33]:
#using lambda function extracting year from datetime 
year=lambda x: x.year
year(now)

2023

In [35]:
import pandas as pd

import numpy as np 



df = pd.DataFrame(np.array([[4,6,9],[5,1,3]]))



print(df.shape)

(2, 3)

In [2]:
import pandas as pnd

pnd.Series([1,2], index= ['a','b'])

a    1
b    2
dtype: int64

In [37]:
df.loc[:,:]

   0  1  2
0  4  6  9
1  5  1  3

In [38]:
df[:]

   0  1  2
0  4  6  9
1  5  1  3

In [41]:
import pandas as pd

# create a sample dataframe
df = pd.DataFrame({
    'A': ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
    'B': ['one', 'one', 'two', 'three', 'two', 'two', 'one', 'three'],
    'C': [1, 2, 3, 4, 5, 6, 7, 8],
    'D': [10, 20, 30, 40, 50, 60, 70, 80]
})

df2=df.groupby('A',axis=1)
print(df2)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000021AD593D960>

# Error and Exception handling

# File not found error

In [46]:
try:
    f=open(r'C:\Users\Futurense\Downloads\test_log.txt')
except FileNotFoundError:
    print('Sorry! This file does not exist')

Sorry! This file does not exist

# name error

In [48]:
try:
    f=open(r'C:\Users\Futurense\Downloads\testlog.txt')
    var=dfsd
except FileNotFoundError:
    print('Sorry! This file does not exist')

NameError: name 'dfsd' is not defined

In [3]:
try:
    f=open(r'C:\Users\Futurense\Downloads\testlog.txt')
    var=dfsd
except FileNotFoundError:
    print('Sorry! This file does not exist')
except NameError:
    print('There is a name error')

There is a name error

# opening and closing file

In [51]:
try:
    f=open(r'C:\Users\Futurense\Downloads\testlog.txt')
    
except FileNotFoundError:
    print('Sorry! This file does not exist')
except NameError:
    print('There ia name error')
else:
    print(f.read())
    f.close()

Date: 2024-04-11
Author: Chirantan
Description: This is a sample log file

Okay, so this is a sample entry.
I'm going to write a few more lines here.
For the sake of this session, let's pretend this log file is thousands and thousands of lines... okay?

In [53]:
try:
    f=open(r'C:\Users\Futurense\Downloads\testlg.txt')
    
except FileNotFoundError:
    print('Sorry! This file does not exist')
except NameError:
    print('There ia name error')
else:
    print(f.read())
    f.close()
finally:
    print('Excecuting the finally block')

Sorry! This file does not exist
Excecuting the finally block

In [57]:
n1=int(input('Enter the input: '))
n2=int(input('enter another number: '))

try:
    print(n2/n1)
except ZeroDivisionError:
    print('Error: Cannot divide with zero')

Enter the input: 0
enter another number: 2
Error: Cannot divide with zero

In [58]:

#In this example, we try to access an element of a list that is out of range. 
#If the index is greater than the length of the list, an IndexError will be raised, 
#and we handle it using an except block.
 
# Create a list of integers
nums = [1, 2, 3, 4, 5]
 
# Try to access an element that is out of range
try:
    num = nums[1]
    print(num)
 
except IndexError:
    print("Error: Index out of range")

try:
    n1=int(input('Enter the input: '))
    
except ValueError:
    print('Please enter an integer')

Enter the input: fef
Please enter an integer

# 14th April

# Functions

In [59]:
import numpy as np

 **1.Sum of even elements in a given list**

In [65]:
l=list(map(int, input().split()))

def sum_of_even(l: list) -> list:
    return sum([x for x in l if x%2==0])

print(f'sum of the even elements in {l} is: ',sum_of_even(l))

1 2 3 4 5 6
sum of the even elements in [1, 2, 3, 4, 5, 6] is:  12

**2.Unique elements in a given list**

In [66]:
l=list(map(int, input().split()))

def unique_elements(l:list)->list:
    return list(set(l))

uni=unique_elements(l)

print(f'Unique elements in {l} are: ',uni)

1 2 3 1 3 2 3 1 5 6 1 8 1 98 1 2 4 5 6 7
Unique elements in [1, 2, 3, 1, 3, 2, 3, 1, 5, 6, 1, 8, 1, 98, 1, 2, 4, 5, 6, 7] are:  [1, 2, 3, 98, 5, 6, 4, 8, 7]

**3.intersected elements in 2 elements**

In [67]:
l1=list(map(int, input().split()))
l2=list(map(int, input().split()))

def common_el(l1:list,l2:list)->list:
    return list(set(l1).intersection(set(l2)))

print(common_el(l1,l2))

1 2 3 45 5
2 3 5 23
[2, 3, 5]

**4.product of numbers in the list**

In [73]:
l=list(map(int, input().split()))

def product_of_numbers(l:list)->int:
    fact=1
    for i in l:
        fact=fact*i
    return fact

print(f'The product of numbers in {l}: {product_of_numbers(l)}')

1 2 3 1
The product of numbers in [1, 2, 3, 1]: [1, 2, 3, 1]

**5.elements with more than 5 characters**

In [68]:
l1=list(map(str, input().split()))

def strings_more_than_len_4(l1:list)->list:
    return [x for x in l1 if len(x)>4]

ans=strings_more_than_len_4(l1)
print(f'strings who have more than 4 charcters: ',ans)

sfffsf sdfsdfsdfds fsfsfs fdf safs asa asfasf
strings who have more than 4 charcters:  ['sfffsf', 'sdfsdfsdfds', 'fsfsfs', 'asfasf']

**6.odd numbers in a list**

In [76]:
l1=list(map(int, input().split()))

def odd_numbers_in_list(l1:list)->list:
    return [x for x in l1 if x%2!=0]

print(f'Odd numbers in {l1} is:{odd_numbers_in_list(l1)}')

1 2 3 4 5 56 6 7
Odd numbers in [1, 2, 3, 4, 5, 56, 6, 7] is:[1, 3, 5, 7]

**7.list of strings that contain letter a**

In [79]:
l1=list(map(str, input().split()))

def str_contains_a(l1:list)->list:
    return [i for i in l1 if 'a' in i]

print(str_contains_a(l1))

asdsa asdad sdf
['asdsa', 'asdad']

**8.largest number inside the list**

In [69]:
l=list(map(int, input().split()))

def largest_el_list(l:list)->list:
    return max(l)
print(f'largest element in {l} is: {largest_el_list(l)}')

1 2 3 4 1 2 4 123 1 2 1 3 1 3 1
largest element in [1, 2, 3, 4, 1, 2, 4, 123, 1, 2, 1, 3, 1, 3, 1] is: 123

**9.word that startswith letter 'a'**

In [80]:
l=list(map(str, input().split()))

def word_startswith_a(l:list)->list:
    return [i for i in l if i[0].lower()=='a']
print(word_startswith_a(l))

asdsf ads gf dfsd asd Assfd
['asdsf', 'ads', 'asd', 'Assfd']

**10.list of numbers divisible by 3**

In [81]:
l=list(map(int, input().split()))

def div_by_3(l:list)->list:
    return [x for x in l if x%3==0]

print(f'List of integers that are divisible by 3 are: {div_by_3(l)}')

1 2 3 3 12 13 15 21 23 114 12
List of integers that are divisible by 3 are: [3, 3, 12, 15, 21, 114, 12]

**11.Return the elements that are only in one of the lists**

In [82]:
l1=list(map(int, input().split()))
l2=list(map(int, input().split()))

def numbers_once(l1:list, l2:list)->list:
    return list(set(l1).symmetric_difference(set(l2)))

print(f'Elements that are present in only once are: {numbers_once(l1,l2)}')

1 2 43 4 1 3
1 4 5 6 7 1 2 5 121 3 43
Elements that are present in only once are: [5, 6, 7, 121]

**12.each number doubled**

In [83]:
l=list(map(int, input().split()))

def double_the_number(l:list)->list:
    return [x*2 for x in l]

print(double_the_number(l))

1 2 3 4 54
[2, 4, 6, 8, 108]

**13.reversing the given string**

In [86]:
l=input()

def reverse_String(l:str)->str:
    return ' '.join([word[::-1] for word in l.split()])

print(reverse_String(l))

Welcome to the Real World. It sucks!
emocleW ot eht laeR .dlroW tI !skcus

**14.Square the each number**

In [87]:
l=list(map(int, input().split()))


def each_number_squared(l:list)->list:
    return [x**2 for x in l]

print(each_number_squared(l))

1 2 3 4 5 6 6 6
[1, 4, 9, 16, 25, 36, 36, 36]