# Classes and Instance

In [1]:
# Static and anonymous or Lambda functions
# Data and functions in class are called as attributes and methods

#for each individual employee will have a name, dept, dept_id, salary etc
#each employee that we create in the employee class will be ab instance of that class

class employee:
    pass

emp1=employee()
emp2=employee()

print(emp1)
print(emp2)
#emp1 and emp2 are called as instances and they are unique
#they are executed and mapped to different addresses

<__main__.employee object at 0x0000023726ECCE80>
<__main__.employee object at 0x0000023726ECE800>

In [3]:

#EACH OF THESE INSTANCES HAVE ATTRIBUTES THAT ARE UNIQUE TO THEM
emp1.first='Chirantan'
emp1.last='Lonkar'
emp1.email='Chirantan.lonkar@xyz.com'
emp1.salary=100000

emp2.first='Xavier'
emp2.last='Pinto'
emp2.email='xavier.pinto@xyz.com'
emp2.salary=120000

print(emp1.email)
print(emp2.email)
print(emp1.salary)

Chirantan.lonkar@xyz.com
xavier.pinto@xyz.com
100000

In [ ]:
# It is impossible to define specific attributes to instances in the class
# say when you have 1000 employees, you won't do it manually
# you want to set it when it is created automatically and it is prone to error when done manually
 
# to make this setup automatic we use the __init__ method #dunder method #magic method
# Inside the class Employee, define the special __init__ method
# When you create a function/methods inside a class, they receive the instance as the 1st arguement automatically
# by convention we should call the instance self
# after self, we can mention what other arguements do we want to specify/accept
 
# Then within the __init__ method set all the instance variables using self.first , self.last ,....

In [4]:
class Employee:
    '''We are defining a method/function'''
    def __init__(self,first,last,salary):  ##dunder method
        self.first=first
        self.last=last
        self.salary=salary
        self.email=first+'.'+last+'@xyz.com'
        
#now we have defined it, the instances are passed automatically, we can just pass those in the instances below

emp1=Employee('Chirantan','Lonkar',100000)
emp2=Employee('Xavier','pinto',120000)

#when we run this, employee 1 ispassed in self in the __init__ method and then

In [5]:
emp1.salary

100000

In [6]:
class Employee:
    '''We are defining a method/function'''
    def __init__(self,first,last,salary):
        self.first=first
        self.last=last
        self.salary=salary
        self.email=first+'.'+last+'@xyz.com'
        
    def Full_name(self):
        return '{} {}'.format(self.first, self.last)
    
    
    
emp1=Employee('Chirantan','Lonkar',100000)
emp2=Employee('Xavier','pinto',120000)

#way-1
print(emp1.Full_name())
print(emp2.Full_name())

Chirantan Lonkar
Xavier pinto

In [7]:
#way-2
emp1.Full_name()

'Chirantan Lonkar'

In [8]:
#way-3:: Using class name: Employee
#We have to pass instance inside the method
Employee.Full_name(emp1)

'Chirantan Lonkar'

# Class variables

In [9]:
class Employee:
    '''We are defining a method/function'''
    def __init__(self,first,last,salary):
        self.first=first
        self.last=last
        self.salary=salary
        self.email=first+'.'+last+'@xyz.com'
        
    def Full_name(self):
        return '{} {}'.format(self.first, self.last)
    
    def apply_raise(self):
        self.salary=int(self.salary*1.04) #setting it int so that we round the value, raising by 4%
        
emp1=Employee('Chirantan','Lonkar',100000)
emp2=Employee('Xavier','pinto',120000)


print(emp1.salary)
emp1.apply_raise()
print(emp1.salary)


print(emp2.salary)
emp2.apply_raise()
print(emp2.salary)

100000
104000
120000
124800

In [12]:
class Employee:
    '''We are defining a method/function'''
    raise_amount=1.04
    def __init__(self,first,last,salary):
        self.first=first
        self.last=last
        self.salary=salary
        self.email=first+'.'+last+'@xyz.com'
        
    def Full_name(self):
        return '{} {}'.format(self.first, self.last)
    
    def apply_raise(self):
        self.salary=int(self.salary*self.raise_amount) #setting it int so that we round the value, raising by 4%
    # setting it int so we have round value and raising by 4 %, 
        
        
emp1 = Employee('Kousik','Dutta',1000000)      
emp2 = Employee('Akshay','Nikam', 1200000) 

print(emp1.salary)
emp1.apply_raise() # instancename.function_name
print(emp1.salary)
emp2.apply_raise()
print(emp2.salary)

## we cans ee the raise being applied

1000000
1040000
1248000

# Inheritance

In [13]:
class Developer(Employee):
    pass

dev_1=Developer('Chirantan','Lonkar',100000)
dev_2=Developer('Xavier','Pinto',120000)

print(dev_1.email)
print(dev_2.email)

Chirantan.Lonkar@xyz.com
Xavier.Pinto@xyz.com

In [14]:
class Employee:
    '''We are defining a method/function'''
    raise_amount=1.04
    def __init__(self,first,last,salary):
        self.first=first
        self.last=last
        self.salary=salary
        self.email=first+'.'+last+'@xyz.com'
        
    def Full_name(self):
        return '{} {}'.format(self.first, self.last)
    
    def apply_raise(self):
        self.salary=int(self.salary*self.raise_amount)


class Developer(Employee):
    raise_amount=1.10
    

dev_1=Developer('Chirantan','Lonkar',100000)
dev_2=Developer('Xavier','Pinto',120000)

print(dev_1.email)
print(dev_1.salary)
dev_1.apply_raise()
print(dev_1.salary)



print(dev_2.email)
print(dev_2.salary)
dev_2.apply_raise()
print(dev_2.salary)

Chirantan.Lonkar@xyz.com
100000
110000
Xavier.Pinto@xyz.com
120000
132000

In [17]:
class Employee:
    
    raise_amount = 1.04
    
    def __init__(self,first,last,salary):
        self.first = first
        self.last = last
        self.salary = salary
        self.email = first + '.' + last + '@' + '@xyz.com'
    
    # define a method for full name
    # Note, every method inside the class automatically takes the instance as the first arguement
    
    def Full_Name(self):
        return '{} {}'.format(self.first ,self.last)
    
    # define a class variable
    def apply_raise(self):
        self.salary = int(self.salary * self.raise_amount) # when we access class variables, we need to access through class itself or instance
                                        # or you can also do Employee.raise  
 
class Developer(Employee): # we mention Employee which states that class Developer will inherit from class Employee
    raise_amount = 1.10
    
    def __init__(self,first,last,salary,prog_lang):
        
        # now we do not define the first,last,salary attributes from employee class
        # for maintenance purposes, we will use super method which will take care of those attributes from employee class
        super().__init__(first,last,salary)
        self.prog_lang = prog_lang
        
        
# Now once we have defined it, the instances are passed automatically, we can just pass those in the instances below
    
dev_1 = Developer('Chirantan','Lonkar',100000,'python') # we have now added the prog_lang attribute too
    
dev_2 = Developer('Xavier','Pinto',120000,'Java')
 
print(dev_1.email)
print(dev_1.prog_lang)
print(dev_2.prog_lang)
 
#print(help(Developer)) # this will help you understand how this class worked in detail
 
 
# print(dev_1.salary)
# dev_1.apply_raise()
# print(dev_1.salary)
# print(Developer.raise_amount)
 
 
# we can see the raise being applied, but it has used developer class's raise amount

Chirantan.Lonkar@@xyz.com
python
Java

In [1]:
import pandas as pd

In [2]:
sales_data = {'Month': ['January', 'February', 'March', 'April'],
              'Product A': [100, 150, 200, 250],
              'Product B': [75, 125, 175, 225]}
df1 = pd.DataFrame(sales_data)
df1

      Month  Product A  Product B
0   January        100         75
1  February        150        125
2     March        200        175
3     April        250        225

In [6]:
df1_melted = pd.melt(df1, id_vars=['Month'], var_name='Product', value_name='Quantity')
df1_melted

      Month    Product  Quantity
0   January  Product A       100
1  February  Product A       150
2     March  Product A       200
3     April  Product A       250
4   January  Product B        75
5  February  Product B       125
6     March  Product B       175
7     April  Product B       225

In [7]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 11.9/11.9 MB 3.7 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp310-cp310-win_amd64.whl size=247958 sha256=fcaf8290aa18795c4cfdf107f6b2706667dc9eeea9ac60e0043d510e4176f211
  Stored in directory: c:\users\futurense\appdata\local\pip\cache\wheels\3e\7f\a3\928a40d1ffd01dd16057f308042377afc505d56145375adf40
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

In [8]:
import mysql.connector

In [19]:
db=mysql.connector.connect(
host='localhost',
user='root',
passwd='Bunny@51249',
database='TEST_MUMBAI'
)

In [23]:
db

In [24]:
mycursor=db.cursor()

mycursor.execute('CREATE DATABASE TEST_MUMBAI')

In [26]:
mycursor.execute('CREATE TABLE Person (name VARCHAR(50),age SMALLINT UNSIGNED, personID INT PRIMARY KEY AUTO_INCREMENT)')

In [28]:
mycursor.execute("DESCRIBE Person")

In [29]:
for x in mycursor:
    print(x)

('name', 'varchar(50)', 'YES', '', None, '')
('age', 'smallint(5) unsigned', 'YES', '', None, '')
('personID', 'int(11)', 'NO', 'PRI', None, 'auto_increment')

In [36]:
mycursor.execute('INSERT INTO Person(name, age) VALUES(%s,%s)', ('Bharathan',24))
db.commit()

In [37]:
mycursor.execute('SELECT * FROM Person')

In [38]:
for x in mycursor:
    print(x)

('Rajender', 25, 1)
('Rakesh', 24, 2)
('Bharathan', 24, 3)

In [39]:
from datetime import datetime
db=mysql.connector.connect(
host='localhost',
user='root',
passwd='',
database='TEST_MUMBAI'
)

In [41]:
mysursor=db.cursor

In [44]:
mycursor.execute("CREATE TABLE mytable (name VARCHAR(50), created_on DATETIME, gender ENUM('M','F','O'), ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT)")
# ENUM helps you select mutliple values
# datetime is the datetime python object

In [57]:
mycursor.execute("INSERT INTO mytable(name,created_on,gender) VALUES(%s,%s,%s)", ('Rakesh',datetime.now(),'M'))

db.commit()

In [58]:
mycursor.execute("Select * from mytable where gender='M'")

In [59]:
for x in mycursor:
    print(x)

('Akhil', datetime.datetime(2023, 4, 19, 15, 34, 34), 'M', 1)
('Rajender', datetime.datetime(2023, 4, 19, 15, 37, 53), 'M', 3)
('Rakesh', datetime.datetime(2023, 4, 19, 15, 38, 16), 'M', 4)

In [60]:
db.commit()

In [61]:
#modify the data inside the table
mycursor.execute("ALTER TABLE mytable ADD COLUMN food VARCHAR(50) NOT NULL")

In [62]:
mycursor.execute('describe mytable')

In [63]:
for x in mycursor:
    print(x)

('name', 'varchar(50)', 'YES', '', None, '')
('created_on', 'datetime', 'YES', '', None, '')
('gender', "enum('M','F','O')", 'YES', '', None, '')
('ID', 'int(11)', 'NO', 'PRI', None, 'auto_increment')
('food', 'varchar(50)', 'NO', '', None, '')

In [64]:
#say we want to drop the food column
mycursor.execute('alter table mytable drop food')

In [65]:
mycursor.execute('describe mytable')

In [66]:
for x in mycursor:
    print(x)

('name', 'varchar(50)', 'YES', '', None, '')
('created_on', 'datetime', 'YES', '', None, '')
('gender', "enum('M','F','O')", 'YES', '', None, '')
('ID', 'int(11)', 'NO', 'PRI', None, 'auto_increment')

In [67]:
#Changing the names of the columns
mycursor.execute('alter table mytable change name first_name varchar(50)')

In [68]:
mycursor.execute('describe mytable')

In [69]:
for x in mycursor:
    print(x)

('first_name', 'varchar(50)', 'YES', '', None, '')
('created_on', 'datetime', 'YES', '', None, '')
('gender', "enum('M','F','O')", 'YES', '', None, '')
('ID', 'int(11)', 'NO', 'PRI', None, 'auto_increment')

In [70]:
import sqlite3

In [71]:
conn=sqlite3.connect('mytable.db')

In [72]:
c=conn.cursor()

In [73]:
for i in c:
    print(i)

In [75]:
conn.commit()

# Regular Expressions

In [76]:
print('\d\d\d')

\d\d\d

In [77]:
#r-- raw string literal

print(r'\t chirantan is mad')

\t chirantan is mad

In [78]:
print('\t chirantan is mad')

	 chirantan is mad

In [81]:
x=123-123-1234
print('\d\d\d-\d\d\d-\d\d\d\d',x)

print('\d{3}-\d{3}-\d{4}')

\d\d\d-\d\d\d-\d\d\d\d -1234

In [88]:
name='Chirantan'
company='Futurense'

print('My name is {}. I work at {}'.format(name, company))

My name is Chirantan. I work at Futurense

In [89]:
text='The phone number of the agent is 444-555-1234. Call soon!'

In [90]:
'phone' in text

True

In [91]:
import re

In [97]:
pattern='phone'

In [98]:
re.search(pattern, text)

In [99]:
#or
my_match=re.search(pattern, text)
my_match.span()  #initial index-end index

(4, 9)

In [100]:
text_redefined='My phone is a new phone'
match=re.search(pattern, text_redefined)
match.span()

(3, 8)

In [101]:
all_matches=re.findall('phone',text_redefined)
all_matches

['phone', 'phone']

In [110]:
ing=re.finditer(pattern, text_redefined)

In [111]:
for i in ing:
    print(i)

<re.Match object; span=(3, 8), match='phone'>
<re.Match object; span=(18, 23), match='phone'>

In [112]:
text

'The phone number of the agent is 444-555-1234. Call soon!'

In [113]:
pattern=r'\d\d\d-\d\d\d-\d\d\d\d'

In [114]:
phone_number=re.search(pattern, text)

In [115]:
phone_number

In [116]:
phone_number.group()

'444-555-1234'

In [118]:
#the or operator

re.search('man|woman', 'This woman was in Los Angeles')

In [119]:
#findall function
re.findall(r'.at','The cat in that hat sat')

['cat', 'hat', 'hat', 'sat']

In [121]:
re.findall(r'.at','The cat in that hat sat and splat')

['cat', 'hat', 'hat', 'sat', 'lat']

In [122]:
import re



text_to_search = '''
abcdefghijklmnopqurtuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
1234567890
Ha HaHa
MetaCharacters (Need to be escaped):
. ^ $ * + ? {​​ }​​ [ ] \ | ( )
coreyms.com
321-555-4321  
123.555.1234
123*555*1234
800-555-1234
900-555-1234
Mr. Schafer
Mr Smith
cat
mat
pat
bat
Ms Davis
Mrs. Robinson
Mr. T
'''


### regular expression is nothing but finding pattern
# r is basically a raw string
# you can removewhite space which are very begining and tailing, 
# in between if you have white space, you will be using replace function

In [123]:
pattern=re.compile(r'abc')

In [124]:
matches=pattern.finditer(text_to_search)
matches

In [125]:
type(matches)

callable_iterator

In [126]:
for i in matches:
    print(i)

<re.Match object; span=(1, 4), match='abc'>

In [ ]:
.       - Any Character Except New Line
\d      - Digit (0-9)
\D      - Not a Digit (0-9)
\w      - Word Character (a-z, A-Z, 0-9, _)
\W      - Not a Word Character
\s      - Whitespace (space, tab, newline)
\S      - Not Whitespace (space, tab, newline)
 
\b      - Word Boundary
\B      - Not a Word Boundary
^       - Beginning of a String
$       - End of a String
 
[]      - Matches Characters in brackets
[^ ]    - Matches Characters NOT in brackets
|       - Either Or
( )     - Group
 
Quantifiers:
*       - 0 or More
+       - 1 or More
?       - 0 or One
{3}     - Exact Number
{3,4}   - Range of Numbers (Minimum, Maximum)
 
'\n'
 
#### Sample Regexs ####
 
[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+

In [127]:
#
pattern=re.compile(r'\d')

matcches=pattern.finditer(text_to_search)

for i in matcches:
    print(i)

<re.Match object; span=(55, 56), match='1'>
<re.Match object; span=(56, 57), match='2'>
<re.Match object; span=(57, 58), match='3'>
<re.Match object; span=(58, 59), match='4'>
<re.Match object; span=(59, 60), match='5'>
<re.Match object; span=(60, 61), match='6'>
<re.Match object; span=(61, 62), match='7'>
<re.Match object; span=(62, 63), match='8'>
<re.Match object; span=(63, 64), match='9'>
<re.Match object; span=(64, 65), match='0'>
<re.Match object; span=(155, 156), match='3'>
<re.Match object; span=(156, 157), match='2'>
<re.Match object; span=(157, 158), match='1'>
<re.Match object; span=(159, 160), match='5'>
<re.Match object; span=(160, 161), match='5'>
<re.Match object; span=(161, 162), match='5'>
<re.Match object; span=(163, 164), match='4'>
<re.Match object; span=(164, 165), match='3'>
<re.Match object; span=(165, 166), match='2'>
<re.Match object; span=(166, 167), match='1'>
<re.Match object; span=(170, 171), match='1'>
<re.Match object; span=(171, 172), match='2'>
<re.Match object; span=(172, 173), match='3'>
<re.Match object; span=(174, 175), match='5'>
<re.Match object; span=(175, 176), match='5'>
<re.Match object; span=(176, 177), match='5'>
<re.Match object; span=(178, 179), match='1'>
<re.Match object; span=(179, 180), match='2'>
<re.Match object; span=(180, 181), match='3'>
<re.Match object; span=(181, 182), match='4'>
<re.Match object; span=(183, 184), match='1'>
<re.Match object; span=(184, 185), match='2'>
<re.Match object; span=(185, 186), match='3'>
<re.Match object; span=(187, 188), match='5'>
<re.Match object; span=(188, 189), match='5'>
<re.Match object; span=(189, 190), match='5'>
<re.Match object; span=(191, 192), match='1'>
<re.Match object; span=(192, 193), match='2'>
<re.Match object; span=(193, 194), match='3'>
<re.Match object; span=(194, 195), match='4'>
<re.Match object; span=(196, 197), match='8'>
<re.Match object; span=(197, 198), match='0'>
<re.Match object; span=(198, 199), match='0'>
<re.Match object; span=(200, 201), match='5'>
<re.Match object; span=(201, 202), match='5'>
<re.Match object; span=(202, 203), match='5'>
<re.Match object; span=(204, 205), match='1'>
<re.Match object; span=(205, 206), match='2'>
<re.Match object; span=(206, 207), match='3'>
<re.Match object; span=(207, 208), match='4'>
<re.Match object; span=(209, 210), match='9'>
<re.Match object; span=(210, 211), match='0'>
<re.Match object; span=(211, 212), match='0'>
<re.Match object; span=(213, 214), match='5'>
<re.Match object; span=(214, 215), match='5'>
<re.Match object; span=(215, 216), match='5'>
<re.Match object; span=(217, 218), match='1'>
<re.Match object; span=(218, 219), match='2'>
<re.Match object; span=(219, 220), match='3'>
<re.Match object; span=(220, 221), match='4'>

In [128]:
pattern=re.compile(r'\D')
matches=pattern.finditer(text_to_search)

for i in matches:
    print(i)

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Match object; span=(23, 24), match='w'>
<re.Match object; span=(24, 25), match='x'>
<re.Match object; span=(25, 26), match='y'>
<re.Match object; span=(26, 27), match='z'>
<re.Match object; span=(27, 28), match='\n'>
<re.Match object; span=(28, 29), match='A'>
<re.Match object; span=(29, 30), match='B'>
<re.Match object; span=(30, 31), match='C'>
<re.Match object; span=(31, 32), match='D'>
<re.Match object; span=(32, 33), match='E'>
<re.Match object; span=(33, 34), match='F'>
<re.Match object; span=(34, 35), match='G'>
<re.Match object; span=(35, 36), match='H'>
<re.Match object; span=(36, 37), match='I'>
<re.Match object; span=(37, 38), match='J'>
<re.Match object; span=(38, 39), match='K'>
<re.Match object; span=(39, 40), match='L'>
<re.Match object; span=(40, 41), match='M'>
<re.Match object; span=(41, 42), match='N'>
<re.Match object; span=(42, 43), match='O'>
<re.Match object; span=(43, 44), match='P'>
<re.Match object; span=(44, 45), match='Q'>
<re.Match object; span=(45, 46), match='R'>
<re.Match object; span=(46, 47), match='S'>
<re.Match object; span=(47, 48), match='T'>
<re.Match object; span=(48, 49), match='U'>
<re.Match object; span=(49, 50), match='V'>
<re.Match object; span=(50, 51), match='W'>
<re.Match object; span=(51, 52), match='X'>
<re.Match object; span=(52, 53), match='Y'>
<re.Match object; span=(53, 54), match='Z'>
<re.Match object; span=(54, 55), match='\n'>
<re.Match object; span=(65, 66), match='\n'>
<re.Match object; span=(66, 67), match='H'>
<re.Match object; span=(67, 68), match='a'>
<re.Match object; span=(68, 69), match=' '>
<re.Match object; span=(69, 70), match='H'>
<re.Match object; span=(70, 71), match='a'>
<re.Match object; span=(71, 72), match='H'>
<re.Match object; span=(72, 73), match='a'>
<re.Match object; span=(73, 74), match='\n'>
<re.Match object; span=(74, 75), match='M'>
<re.Match object; span=(75, 76), match='e'>
<re.Match object; span=(76, 77), match='t'>
<re.Match object; span=(77, 78), match='a'>
<re.Match object; span=(78, 79), match='C'>
<re.Match object; span=(79, 80), match='h'>
<re.Match object; span=(80, 81), match='a'>
<re.Match object; span=(81, 82), match='r'>
<re.Match object; span=(82, 83), match='a'>
<re.Match object; span=(83, 84), match='c'>
<re.Match object; span=(84, 85), match='t'>
<re.Match object; span=(85, 86), match='e'>
<re.Match object; span=(86, 87), match='r'>
<re.Match object; span=(87, 88), match='s'>
<re.Match object; span=(88, 89), match=' '>
<re.Match object; span=(89, 90), match='('>
<re.Match object; span=(90, 91), match='N'>
<re.Match object; span=(91, 92), match='e'>
<re.Match object; span=(92, 93), match='e'>
<re.Match object; span=(93, 94), match='d'>
<re.Match object; span=(94, 95), match=' '>
<re.Match object; span=(95, 96), match='t'>
<re.Match object; span=(96, 97), match='o'>
<re.Match object; span=(97, 98), match=' '>
<re.Match object; span=(98, 99), match='b'>
<re.Match object; span=(99, 100), match='e'>
<re.Match object; span=(100, 101), match=' '>
<re.Match object; span=(101, 102), match='e'>
<re.Match object; span=(102, 103), match='s'>
<re.Match object; span=(103, 104), match='c'>
<re.Match object; span=(104, 105), match='a'>
<re.Match object; span=(105, 106), match='p'>
<re.Match object; span=(106, 107), match='e'>
<re.Match object; span=(107, 108), match='d'>
<re.Match object; span=(108, 109), match=')'>
<re.Match object; span=(109, 110), match=':'>
<re.Match object; span=(110, 111), match='\n'>
<re.Match object; span=(111, 112), match='.'>
<re.Match object; span=(112, 113), match=' '>
<re.Match object; span=(113, 114), match='^'>
<re.Match object; span=(114, 115), match=' '>
<re.Match object; span=(115, 116), match='$'>
<re.Match object; span=(116, 117), match=' '>
<re.Match object; span=(117, 118), match='*'>
<re.Match object; span=(118, 119), match=' '>
<re.Match object; span=(119, 120), match='+'>
<re.Match object; span=(120, 121), match=' '>
<re.Match object; span=(121, 122), match='?'>
<re.Match object; span=(122, 123), match=' '>
<re.Match object; span=(123, 124), match='{'>
<re.Match object; span=(124, 125), match='\u200b'>
<re.Match object; span=(125, 126), match='\u200b'>
<re.Match object; span=(126, 127), match=' '>
<re.Match object; span=(127, 128), match='}'>
<re.Match object; span=(128, 129), match='\u200b'>
<re.Match object; span=(129, 130), match='\u200b'>
<re.Match object; span=(130, 131), match=' '>
<re.Match object; span=(131, 132), match='['>
<re.Match object; span=(132, 133), match=' '>
<re.Match object; span=(133, 134), match=']'>
<re.Match object; span=(134, 135), match=' '>
<re.Match object; span=(135, 136), match='\\'>
<re.Match object; span=(136, 137), match=' '>
<re.Match object; span=(137, 138), match='|'>
<re.Match object; span=(138, 139), match=' '>
<re.Match object; span=(139, 140), match='('>
<re.Match object; span=(140, 141), match=' '>
<re.Match object; span=(141, 142), match=')'>
<re.Match object; span=(142, 143), match='\n'>
<re.Match object; span=(143, 144), match='c'>
<re.Match object; span=(144, 145), match='o'>
<re.Match object; span=(145, 146), match='r'>
<re.Match object; span=(146, 147), match='e'>
<re.Match object; span=(147, 148), match='y'>
<re.Match object; span=(148, 149), match='m'>
<re.Match object; span=(149, 150), match='s'>
<re.Match object; span=(150, 151), match='.'>
<re.Match object; span=(151, 152), match='c'>
<re.Match object; span=(152, 153), match='o'>
<re.Match object; span=(153, 154), match='m'>
<re.Match object; span=(154, 155), match='\n'>
<re.Match object; span=(158, 159), match='-'>
<re.Match object; span=(162, 163), match='-'>
<re.Match object; span=(167, 168), match=' '>
<re.Match object; span=(168, 169), match=' '>
<re.Match object; span=(169, 170), match='\n'>
<re.Match object; span=(173, 174), match='.'>
<re.Match object; span=(177, 178), match='.'>
<re.Match object; span=(182, 183), match='\n'>
<re.Match object; span=(186, 187), match='*'>
<re.Match object; span=(190, 191), match='*'>
<re.Match object; span=(195, 196), match='\n'>
<re.Match object; span=(199, 200), match='-'>
<re.Match object; span=(203, 204), match='-'>
<re.Match object; span=(208, 209), match='\n'>
<re.Match object; span=(212, 213), match='-'>
<re.Match object; span=(216, 217), match='-'>
<re.Match object; span=(221, 222), match='\n'>
<re.Match object; span=(222, 223), match='M'>
<re.Match object; span=(223, 224), match='r'>
<re.Match object; span=(224, 225), match='.'>
<re.Match object; span=(225, 226), match=' '>
<re.Match object; span=(226, 227), match='S'>
<re.Match object; span=(227, 228), match='c'>
<re.Match object; span=(228, 229), match='h'>
<re.Match object; span=(229, 230), match='a'>
<re.Match object; span=(230, 231), match='f'>
<re.Match object; span=(231, 232), match='e'>
<re.Match object; span=(232, 233), match='r'>
<re.Match object; span=(233, 234), match='\n'>
<re.Match object; span=(234, 235), match='M'>
<re.Match object; span=(235, 236), match='r'>
<re.Match object; span=(236, 237), match=' '>
<re.Match object; span=(237, 238), match='S'>
<re.Match object; span=(238, 239), match='m'>
<re.Match object; span=(239, 240), match='i'>
<re.Match object; span=(240, 241), match='t'>
<re.Match object; span=(241, 242), match='h'>
<re.Match object; span=(242, 243), match='\n'>
<re.Match object; span=(243, 244), match='c'>
<re.Match object; span=(244, 245), match='a'>
<re.Match object; span=(245, 246), match='t'>
<re.Match object; span=(246, 247), match='\n'>
<re.Match object; span=(247, 248), match='m'>
<re.Match object; span=(248, 249), match='a'>
<re.Match object; span=(249, 250), match='t'>
<re.Match object; span=(250, 251), match='\n'>
<re.Match object; span=(251, 252), match='p'>
<re.Match object; span=(252, 253), match='a'>
<re.Match object; span=(253, 254), match='t'>
<re.Match object; span=(254, 255), match='\n'>
<re.Match object; span=(255, 256), match='b'>
<re.Match object; span=(256, 257), match='a'>
<re.Match object; span=(257, 258), match='t'>
<re.Match object; span=(258, 259), match='\n'>
<re.Match object; span=(259, 260), match='M'>
<re.Match object; span=(260, 261), match='s'>
<re.Match object; span=(261, 262), match=' '>
<re.Match object; span=(262, 263), match='D'>
<re.Match object; span=(263, 264), match='a'>
<re.Match object; span=(264, 265), match='v'>
<re.Match object; span=(265, 266), match='i'>
<re.Match object; span=(266, 267), match='s'>
<re.Match object; span=(267, 268), match='\n'>
<re.Match object; span=(268, 269), match='M'>
<re.Match object; span=(269, 270), match='r'>
<re.Match object; span=(270, 271), match='s'>
<re.Match object; span=(271, 272), match='.'>
<re.Match object; span=(272, 273), match=' '>
<re.Match object; span=(273, 274), match='R'>
<re.Match object; span=(274, 275), match='o'>
<re.Match object; span=(275, 276), match='b'>
<re.Match object; span=(276, 277), match='i'>
<re.Match object; span=(277, 278), match='n'>
<re.Match object; span=(278, 279), match='s'>
<re.Match object; span=(279, 280), match='o'>
<re.Match object; span=(280, 281), match='n'>
<re.Match object; span=(281, 282), match='\n'>
<re.Match object; span=(282, 283), match='M'>
<re.Match object; span=(283, 284), match='r'>
<re.Match object; span=(284, 285), match='.'>
<re.Match object; span=(285, 286), match=' '>
<re.Match object; span=(286, 287), match='T'>
<re.Match object; span=(287, 288), match='\n'>

In [129]:
pattern=re.compile(r'\w')

matches=pattern.finditer(text_to_search)

for i in matches:
    print(i)

<re.Match object; span=(1, 2), match='a'>
<re.Match object; span=(2, 3), match='b'>
<re.Match object; span=(3, 4), match='c'>
<re.Match object; span=(4, 5), match='d'>
<re.Match object; span=(5, 6), match='e'>
<re.Match object; span=(6, 7), match='f'>
<re.Match object; span=(7, 8), match='g'>
<re.Match object; span=(8, 9), match='h'>
<re.Match object; span=(9, 10), match='i'>
<re.Match object; span=(10, 11), match='j'>
<re.Match object; span=(11, 12), match='k'>
<re.Match object; span=(12, 13), match='l'>
<re.Match object; span=(13, 14), match='m'>
<re.Match object; span=(14, 15), match='n'>
<re.Match object; span=(15, 16), match='o'>
<re.Match object; span=(16, 17), match='p'>
<re.Match object; span=(17, 18), match='q'>
<re.Match object; span=(18, 19), match='u'>
<re.Match object; span=(19, 20), match='r'>
<re.Match object; span=(20, 21), match='t'>
<re.Match object; span=(21, 22), match='u'>
<re.Match object; span=(22, 23), match='v'>
<re.Match object; span=(23, 24), match='w'>
<re.Match object; span=(24, 25), match='x'>
<re.Match object; span=(25, 26), match='y'>
<re.Match object; span=(26, 27), match='z'>
<re.Match object; span=(28, 29), match='A'>
<re.Match object; span=(29, 30), match='B'>
<re.Match object; span=(30, 31), match='C'>
<re.Match object; span=(31, 32), match='D'>
<re.Match object; span=(32, 33), match='E'>
<re.Match object; span=(33, 34), match='F'>
<re.Match object; span=(34, 35), match='G'>
<re.Match object; span=(35, 36), match='H'>
<re.Match object; span=(36, 37), match='I'>
<re.Match object; span=(37, 38), match='J'>
<re.Match object; span=(38, 39), match='K'>
<re.Match object; span=(39, 40), match='L'>
<re.Match object; span=(40, 41), match='M'>
<re.Match object; span=(41, 42), match='N'>
<re.Match object; span=(42, 43), match='O'>
<re.Match object; span=(43, 44), match='P'>
<re.Match object; span=(44, 45), match='Q'>
<re.Match object; span=(45, 46), match='R'>
<re.Match object; span=(46, 47), match='S'>
<re.Match object; span=(47, 48), match='T'>
<re.Match object; span=(48, 49), match='U'>
<re.Match object; span=(49, 50), match='V'>
<re.Match object; span=(50, 51), match='W'>
<re.Match object; span=(51, 52), match='X'>
<re.Match object; span=(52, 53), match='Y'>
<re.Match object; span=(53, 54), match='Z'>
<re.Match object; span=(55, 56), match='1'>
<re.Match object; span=(56, 57), match='2'>
<re.Match object; span=(57, 58), match='3'>
<re.Match object; span=(58, 59), match='4'>
<re.Match object; span=(59, 60), match='5'>
<re.Match object; span=(60, 61), match='6'>
<re.Match object; span=(61, 62), match='7'>
<re.Match object; span=(62, 63), match='8'>
<re.Match object; span=(63, 64), match='9'>
<re.Match object; span=(64, 65), match='0'>
<re.Match object; span=(66, 67), match='H'>
<re.Match object; span=(67, 68), match='a'>
<re.Match object; span=(69, 70), match='H'>
<re.Match object; span=(70, 71), match='a'>
<re.Match object; span=(71, 72), match='H'>
<re.Match object; span=(72, 73), match='a'>
<re.Match object; span=(74, 75), match='M'>
<re.Match object; span=(75, 76), match='e'>
<re.Match object; span=(76, 77), match='t'>
<re.Match object; span=(77, 78), match='a'>
<re.Match object; span=(78, 79), match='C'>
<re.Match object; span=(79, 80), match='h'>
<re.Match object; span=(80, 81), match='a'>
<re.Match object; span=(81, 82), match='r'>
<re.Match object; span=(82, 83), match='a'>
<re.Match object; span=(83, 84), match='c'>
<re.Match object; span=(84, 85), match='t'>
<re.Match object; span=(85, 86), match='e'>
<re.Match object; span=(86, 87), match='r'>
<re.Match object; span=(87, 88), match='s'>
<re.Match object; span=(90, 91), match='N'>
<re.Match object; span=(91, 92), match='e'>
<re.Match object; span=(92, 93), match='e'>
<re.Match object; span=(93, 94), match='d'>
<re.Match object; span=(95, 96), match='t'>
<re.Match object; span=(96, 97), match='o'>
<re.Match object; span=(98, 99), match='b'>
<re.Match object; span=(99, 100), match='e'>
<re.Match object; span=(101, 102), match='e'>
<re.Match object; span=(102, 103), match='s'>
<re.Match object; span=(103, 104), match='c'>
<re.Match object; span=(104, 105), match='a'>
<re.Match object; span=(105, 106), match='p'>
<re.Match object; span=(106, 107), match='e'>
<re.Match object; span=(107, 108), match='d'>
<re.Match object; span=(143, 144), match='c'>
<re.Match object; span=(144, 145), match='o'>
<re.Match object; span=(145, 146), match='r'>
<re.Match object; span=(146, 147), match='e'>
<re.Match object; span=(147, 148), match='y'>
<re.Match object; span=(148, 149), match='m'>
<re.Match object; span=(149, 150), match='s'>
<re.Match object; span=(151, 152), match='c'>
<re.Match object; span=(152, 153), match='o'>
<re.Match object; span=(153, 154), match='m'>
<re.Match object; span=(155, 156), match='3'>
<re.Match object; span=(156, 157), match='2'>
<re.Match object; span=(157, 158), match='1'>
<re.Match object; span=(159, 160), match='5'>
<re.Match object; span=(160, 161), match='5'>
<re.Match object; span=(161, 162), match='5'>
<re.Match object; span=(163, 164), match='4'>
<re.Match object; span=(164, 165), match='3'>
<re.Match object; span=(165, 166), match='2'>
<re.Match object; span=(166, 167), match='1'>
<re.Match object; span=(170, 171), match='1'>
<re.Match object; span=(171, 172), match='2'>
<re.Match object; span=(172, 173), match='3'>
<re.Match object; span=(174, 175), match='5'>
<re.Match object; span=(175, 176), match='5'>
<re.Match object; span=(176, 177), match='5'>
<re.Match object; span=(178, 179), match='1'>
<re.Match object; span=(179, 180), match='2'>
<re.Match object; span=(180, 181), match='3'>
<re.Match object; span=(181, 182), match='4'>
<re.Match object; span=(183, 184), match='1'>
<re.Match object; span=(184, 185), match='2'>
<re.Match object; span=(185, 186), match='3'>
<re.Match object; span=(187, 188), match='5'>
<re.Match object; span=(188, 189), match='5'>
<re.Match object; span=(189, 190), match='5'>
<re.Match object; span=(191, 192), match='1'>
<re.Match object; span=(192, 193), match='2'>
<re.Match object; span=(193, 194), match='3'>
<re.Match object; span=(194, 195), match='4'>
<re.Match object; span=(196, 197), match='8'>
<re.Match object; span=(197, 198), match='0'>
<re.Match object; span=(198, 199), match='0'>
<re.Match object; span=(200, 201), match='5'>
<re.Match object; span=(201, 202), match='5'>
<re.Match object; span=(202, 203), match='5'>
<re.Match object; span=(204, 205), match='1'>
<re.Match object; span=(205, 206), match='2'>
<re.Match object; span=(206, 207), match='3'>
<re.Match object; span=(207, 208), match='4'>
<re.Match object; span=(209, 210), match='9'>
<re.Match object; span=(210, 211), match='0'>
<re.Match object; span=(211, 212), match='0'>
<re.Match object; span=(213, 214), match='5'>
<re.Match object; span=(214, 215), match='5'>
<re.Match object; span=(215, 216), match='5'>
<re.Match object; span=(217, 218), match='1'>
<re.Match object; span=(218, 219), match='2'>
<re.Match object; span=(219, 220), match='3'>
<re.Match object; span=(220, 221), match='4'>
<re.Match object; span=(222, 223), match='M'>
<re.Match object; span=(223, 224), match='r'>
<re.Match object; span=(226, 227), match='S'>
<re.Match object; span=(227, 228), match='c'>
<re.Match object; span=(228, 229), match='h'>
<re.Match object; span=(229, 230), match='a'>
<re.Match object; span=(230, 231), match='f'>
<re.Match object; span=(231, 232), match='e'>
<re.Match object; span=(232, 233), match='r'>
<re.Match object; span=(234, 235), match='M'>
<re.Match object; span=(235, 236), match='r'>
<re.Match object; span=(237, 238), match='S'>
<re.Match object; span=(238, 239), match='m'>
<re.Match object; span=(239, 240), match='i'>
<re.Match object; span=(240, 241), match='t'>
<re.Match object; span=(241, 242), match='h'>
<re.Match object; span=(243, 244), match='c'>
<re.Match object; span=(244, 245), match='a'>
<re.Match object; span=(245, 246), match='t'>
<re.Match object; span=(247, 248), match='m'>
<re.Match object; span=(248, 249), match='a'>
<re.Match object; span=(249, 250), match='t'>
<re.Match object; span=(251, 252), match='p'>
<re.Match object; span=(252, 253), match='a'>
<re.Match object; span=(253, 254), match='t'>
<re.Match object; span=(255, 256), match='b'>
<re.Match object; span=(256, 257), match='a'>
<re.Match object; span=(257, 258), match='t'>
<re.Match object; span=(259, 260), match='M'>
<re.Match object; span=(260, 261), match='s'>
<re.Match object; span=(262, 263), match='D'>
<re.Match object; span=(263, 264), match='a'>
<re.Match object; span=(264, 265), match='v'>
<re.Match object; span=(265, 266), match='i'>
<re.Match object; span=(266, 267), match='s'>
<re.Match object; span=(268, 269), match='M'>
<re.Match object; span=(269, 270), match='r'>
<re.Match object; span=(270, 271), match='s'>
<re.Match object; span=(273, 274), match='R'>
<re.Match object; span=(274, 275), match='o'>
<re.Match object; span=(275, 276), match='b'>
<re.Match object; span=(276, 277), match='i'>
<re.Match object; span=(277, 278), match='n'>
<re.Match object; span=(278, 279), match='s'>
<re.Match object; span=(279, 280), match='o'>
<re.Match object; span=(280, 281), match='n'>
<re.Match object; span=(282, 283), match='M'>
<re.Match object; span=(283, 284), match='r'>
<re.Match object; span=(286, 287), match='T'>

In [130]:
pattern=re.compile(r'\s')
matches=pattern.finditer(text_to_search)

for i in matches:
    print(i)

<re.Match object; span=(0, 1), match='\n'>
<re.Match object; span=(27, 28), match='\n'>
<re.Match object; span=(54, 55), match='\n'>
<re.Match object; span=(65, 66), match='\n'>
<re.Match object; span=(68, 69), match=' '>
<re.Match object; span=(73, 74), match='\n'>
<re.Match object; span=(88, 89), match=' '>
<re.Match object; span=(94, 95), match=' '>
<re.Match object; span=(97, 98), match=' '>
<re.Match object; span=(100, 101), match=' '>
<re.Match object; span=(110, 111), match='\n'>
<re.Match object; span=(112, 113), match=' '>
<re.Match object; span=(114, 115), match=' '>
<re.Match object; span=(116, 117), match=' '>
<re.Match object; span=(118, 119), match=' '>
<re.Match object; span=(120, 121), match=' '>
<re.Match object; span=(122, 123), match=' '>
<re.Match object; span=(126, 127), match=' '>
<re.Match object; span=(130, 131), match=' '>
<re.Match object; span=(132, 133), match=' '>
<re.Match object; span=(134, 135), match=' '>
<re.Match object; span=(136, 137), match=' '>
<re.Match object; span=(138, 139), match=' '>
<re.Match object; span=(140, 141), match=' '>
<re.Match object; span=(142, 143), match='\n'>
<re.Match object; span=(154, 155), match='\n'>
<re.Match object; span=(167, 168), match=' '>
<re.Match object; span=(168, 169), match=' '>
<re.Match object; span=(169, 170), match='\n'>
<re.Match object; span=(182, 183), match='\n'>
<re.Match object; span=(195, 196), match='\n'>
<re.Match object; span=(208, 209), match='\n'>
<re.Match object; span=(221, 222), match='\n'>
<re.Match object; span=(225, 226), match=' '>
<re.Match object; span=(233, 234), match='\n'>
<re.Match object; span=(236, 237), match=' '>
<re.Match object; span=(242, 243), match='\n'>
<re.Match object; span=(246, 247), match='\n'>
<re.Match object; span=(250, 251), match='\n'>
<re.Match object; span=(254, 255), match='\n'>
<re.Match object; span=(258, 259), match='\n'>
<re.Match object; span=(261, 262), match=' '>
<re.Match object; span=(267, 268), match='\n'>
<re.Match object; span=(272, 273), match=' '>
<re.Match object; span=(281, 282), match='\n'>
<re.Match object; span=(285, 286), match=' '>
<re.Match object; span=(287, 288), match='\n'>

In [131]:
sentence = 'Welcome to Futurense Technologies'

pattern = re.compile(r'^Welcome')

matches = pattern.finditer(sentence)

for match in matches:
    print(match)

<re.Match object; span=(0, 7), match='Welcome'>

In [133]:
# match with end using $

sentence = 'Welcome to Futurense Technologies'

pattern = re.compile(r'ense$')

matches = pattern.finditer(sentence)

for match in matches:
    print(match)

In [134]:
pattern=re.compile(r'\d{3}.\d{3}.\d{3}')

matches=pattern.finditer(text_to_search)

for i in matches:
    print(i)

<re.Match object; span=(155, 166), match='321-555-432'>
<re.Match object; span=(170, 181), match='123.555.123'>
<re.Match object; span=(183, 194), match='123*555*123'>
<re.Match object; span=(196, 207), match='800-555-123'>
<re.Match object; span=(209, 220), match='900-555-123'>